### ISSUE TITLE
App name "account" too common, use prefix instead. Ex: "allauth_account"

### ISSUE THREAD

**Issue by RusEu** [pennersr/django-allauth#1509] opened 2016-10-06 16:40 UTC
I already have one application "account" installed, and it gives me an conflict error.
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: account

**Comment by pennersr** [comment] 2016-10-06 17:36
Dupe of #393

**Closed by pennersr** 2016-10-06 17:36 UTC

**Comment by pennersr** [comment] 2026-06-10 19:56
https://codeberg.org/allauth/django-allauth/issues/1509
