### ISSUE TITLE
Way to use django-allauth to login without password ?

### ISSUE THREAD

**Issue by petijean** [pennersr/django-allauth#2691] opened 2020-10-22 10:16 UTC
Hello,
Is there a way to use djang-allauth to login (and signin) users with confirmation mails ?
- To log in (or to sign up), users would only provide their email xx@xx.xx
- a validation mail (whose validity would be time-limited) would be send to xx@xx.xx to enable their authentification
Thanks !

**Comment by 9mido** [comment] 2020-10-23 06:36
So a user has to login with a confirmation email each time? 

I don't think that is a good idea if the email provider account itself is compromised. It allows an easy way for a hacker to login to your website's account. A password is an additional security layer since it is an extra thing a user knows and it could be different than the email provider account's password.

What if allauth was configured where one person can have multiple email addresses? Then something like a typo mistake where a random email address that you accidentally added is not yours and someone else's and that other person could login to your account and lock you out by deleting your original account email.

**Comment by iarp** [comment] 2020-10-24 01:47
If the email provider is compromised then it doesn't matter whether or not the account has a password.

**Comment by pennersr** [comment] 2021-12-14 21:09
Dupe of #1758

**Closed by pennersr** 2021-12-14 21:09 UTC

**Comment by pennersr** [comment] 2026-06-11 17:03
https://codeberg.org/allauth/django-allauth/issues/2691
