### ISSUE TITLE
ImportError: No module named context_processors

### ISSUE THREAD

**Issue by cshimmin** [pennersr/django-allauth#1080] opened 2015-08-05 19:36 UTC
Hi,
Just noticed this issue when I upgraded django-allauth 0.23. All django views are returning this error, which goes away when I revert to 0.21 or earlier.

Please let me know if there's any more info I can give to help debug. I'm using Python 2.7.6 and Django 1.7.6. Here's the stack trace:

```
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/my/project/myapp/views.py", line 246, in index
    resp = render(request, 'myapp/index.html', context)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 46, in render
    context_instance = RequestContext(request, current_app=current_app)
  File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 208, in __init__
    for processor in get_standard_processors() + processors:
  File "/usr/local/lib/python2.7/dist-packages/django/template/context.py", line 186, in get_standard_processors
    func = import_string(path)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named context_processors
```

**Comment by arnaudlimbourg** [comment] 2015-08-06 08:35
@cshimmin As per http://django-allauth.readthedocs.org/en/latest/changelog.html context processors have gone away. You will need to update your templates slightly.

**Comment by cshimmin** [comment] 2015-08-07 02:39
Thanks for the response. It's been many moons since I installed allauth or read the docs... but given your statement I can trace this to the addition of allauth's context processors to `settings.TEMPLATE_CONTEXT_PROCESSORS` when we originally installed allauth in our application. Actually as far as I can tell we're not using any of the allauth template tags, so I suppose we can just remove these.

Does this page need updating, as it still recommends adding these?
http://django-allauth.readthedocs.org/en/latest/installation.html?highlight=context

**Comment by arnaudlimbourg** [comment] 2015-08-07 09:59
The page is correct, context processors indicated are from django and not allauth :) ``'django.template.context_processors.request'``

**Comment by cshimmin** [comment] 2015-08-11 21:07
Oops, my mistake. Thanks for clarifying, I think you can close this, since it seems to have been simply a misunderstanding on my part while upgrading.

**Comment by arnaudlimbourg** [comment] 2015-08-13 08:45
I think you should be able to close it, I'm just a random person and not an allauth contributor :)

**Comment by bittner** [comment] 2015-09-11 19:46
This is a duplicate of #1051 and should be closed.

**Closed** 2015-09-17 17:57 UTC

**Comment by pennersr** [comment] 2026-06-10 19:45
https://codeberg.org/allauth/django-allauth/issues/1080
