### ISSUE TITLE
Integrate local oauth server with django-allauth?

### ISSUE THREAD

**Issue by joshuakoh7** [pennersr/django-allauth#2480] opened 2020-03-08 13:58 UTC
Is there a possibility to add oauth to the username/password login via django-oauth-toolkit or something?

**Comment by pennersr** [comment] 2023-07-06 20:42
Closing -- unclear what the issue is in allauth.

**Closed by pennersr** 2023-07-06 20:42 UTC

**Comment by pennersr** [comment] 2026-06-10 21:00
https://codeberg.org/allauth/django-allauth/issues/2480
