### ISSUE TITLE
reverse with 'linkedin_oauth2_login'

### ISSUE THREAD

**Issue by fab10m** [pennersr/django-allauth#1063] opened 2015-07-28 20:50 UTC
Hi,

I have this code:

``` python
class LoginRequiredMixin(object):    
    @classmethod
    def as_view(self, *args, **initkwargs):        
        view = super(LoginRequiredMixin, self).as_view(*args, **initkwargs)
        login_url = reverse('linkedin_oauth2_login')
        login_url = '{0}?process=login'.format(login_url)
        return login_required(view, login_url=login_url)

class ServiceWizard(LoginRequiredMixin, SessionWizardView):
    some code ....
```
but when I visit the url associated to the view ServiceWizard I get the error "The included urlconf 'myproject.urls' does not appear to have any patterns in it. If you see valid patterns in the file then the issue is probably caused by a circular import."

The strange thig is that if I execute the command 
``` python
print reverse('linkedin_oauth2_login') 
```
in the console all works fine.

Can you help me?

Regards,

Fabio

**Comment by pennersr** [comment] 2015-09-17 18:01
This is indeed a typical symptom of circular imports. The fact that things work on the console and not in a runserver, or vice versa, is caused by slight variations in the import order between the two. All in all, closing, not an allauth issue...

**Closed by pennersr** 2015-09-17 18:01 UTC

**Comment by pennersr** [comment] 2026-06-10 19:44
https://codeberg.org/allauth/django-allauth/issues/1063
