### ISSUE TITLE
Account enumeration via add email address endpoint

### ISSUE THREAD

**Issue by mecampbellsoup** [pennersr/django-allauth#3318] opened 2023-05-22 21:21 UTC
Related to https://github.com/pennersr/django-allauth/issues/1307.

We recently toggled `ACCOUNT_PREVENT_ENUMERATION = True` and no longer allow _unauthenticated_ requests like signup and password reset to enumerate email addresses. This is good!

However we noticed when QA'ing that an authenticated user can still enumerate email addresses by attempting to _add an existing email address_ to their user account via the `/accounts/email` endpoint/view.

![image](https://github.com/pennersr/django-allauth/assets/2043821/fd87336a-ecb7-424f-b045-3ccdb76e3877)

Do you guys think it is in scope for `ACCOUNT_PREVENT_ENUMERATION` configuration to also alter the error message in the API response when `POST /accounts/email` fails due to the email address already existing?

**Comment by pennersr** [comment] 2023-05-23 17:28
Ideally, yes, that is in scope. Although for enumeration to be prevented an error message is not going to cut it. Both flows -- the case of an unregistered vs registered email address -- need to handled in the same manner. If there is a difference in handling these flows, you can use that difference to come to the conclusion that an email address already exists.  Fixing this has quite some impact, because it would mean that an email address that is already taken can still be added, which conflicts with the current data models where email addresses  are typically unique per account (assuming `ACCOUNT_UNIQUE_EMAIL=True`).

**Comment by mecampbellsoup** [comment] 2023-05-23 19:29
Gotcha - I suppose we could handle this ourselves by wrapping the add email view in a custom view and implementing the logic there. I understand how challenging this would be to implement at the allauth layer.

**Comment by pennersr** [comment] 2023-05-24 17:41
Not sure how you would approach this by only altering the view logic? Point is, you need to actually store any of the email addresses added, even if they are duplicates of already existing accounts. If you're not adding them, they won't be displayed, and the user can tell that there is something special to the email address that is not showing up.

**Comment by mecampbellsoup** [comment] 2023-05-24 18:06
> Not sure how you would approach this by only altering the view logic? Point is, you need to actually store any of the email addresses added, even if they are duplicates of already existing accounts. If you're not adding them, they won't be displayed, and the user can tell that there is something special to the email address that is not showing up.

Currently we pass through the response from allauth, so when email exists that's something like `Email address already exists` in the error/response body. The change would be to intercept that and instead say something generic like `If this email address is available, please check your inbox to confirm it`.

**Comment by mecampbellsoup** [comment] 2023-05-24 19:27
We wrap allauth and use it as a hidden internal AJAX API, as opposed to using allauth's HTML. Moreover our UI treats it as "change email" (not add/manage a list of emails). But in general your point is well taken.

**Comment by wgordon17** [comment] 2023-06-10 19:05
It feels like, to solve this, you'd have to alter the logic of `ACCOUNT_UNIQUE_EMAIL=True` to instead of being a unique index on the table, enforce a uniqueness on `email` _and_ `confirmed`. So that _any_ user can just add emails. Then the generic messaging proposed, "If this email address is available, please check your inbox to confirm it", could work. If the user really _does_ own the email address in two places, then we can display the error about multiple uses on the _confirmation_ page, versus on the _adding_ page.

WDYT?

**Comment by wgordon17** [comment] 2023-06-12 18:03
Yes, so _certainly_ doable, but **definitely** not a light lift 😏 (security is _hard_)

**Comment by pennersr** [comment] 2023-06-12 19:50
@wgordon17 Most certainly doable, and given that it is security related it should be done. Will look into prioritizing this.

**Comment by pennersr** [comment] 2023-06-13 20:10
Work in progress: https://github.com/pennersr/django-allauth/tree/feat-unique-together-email-verified

**Comment by pennersr** [comment] 2023-06-16 18:18
To be fixed with #3327

**Closed** 2023-06-16 18:51 UTC
Labels: TODO

**Comment by pennersr** [comment] 2026-06-11 17:20
https://codeberg.org/allauth/django-allauth/issues/3318
