### ISSUE TITLE
SignUp Setting Session ID in Cookie

### ISSUE THREAD

**Issue by srinivasaravind5** [pennersr/django-allauth#2366] opened 2019-10-03 11:13 UTC
I have the setting to of email confirmation to mandatory, still after signup allauth sets the session id in the cookie.

**Comment by muhalitas** [comment] 2020-05-20 16:25
no one cares issues. what a package ha.

**Comment by pennersr** [comment] 2020-10-11 16:07
The signup view is accessing the session, for example to unstash a verified email address. Though, accessing the session should not be mistaken with getting incorrectly authenticated while the email is not confirmed. Closing -- not clear what the issue is here.

**Closed by pennersr** 2020-10-11 16:07 UTC

**Comment by pennersr** [comment] 2026-06-10 20:57
https://codeberg.org/allauth/django-allauth/issues/2366
