### ISSUE TITLE
Apple SSO: switch between service ID and bundle ID as the client ID?

### ISSUE THREAD

**Issue by lee-hodg** [pennersr/django-allauth#2718] opened 2020-11-18 15:55 UTC
For the Apple SSO, there are 2 Client IDs, a Bundle ID and a Services ID. When the flow is started from a mobile iOS device the app would use the Bundle ID as the Client ID, but when it is started from a web app such as react the authorization flow would be started with the Service ID as the Client ID.

How does the django-allauth Apple provider handle these 2 different Client ID? 

There are some comments in the PR thread https://github.com/pennersr/django-allauth/pull/2424 that suggest setting up `SOCIALPROVIDERS` using a comma-delimited string of the 2 client IDs, like `Client id = <APPLE_SERVICE_ID>, <APPLE_APP_ID>`  (https://github.com/pennersr/django-allauth/pull/2424#issuecomment-670597679) however looking at `allauth/socialaccount/providers/apple/client.py` shows that always the first client ID in the string would be used anyway

```
    def get_client_id(self):
        """ We support multiple client_ids, but use the first one for api calls """
        return self.consumer_key.split(",")[0]
```

This means if the Service ID is the first in the settings, then it would ALWAYS be the one used. 

If iOS initiated the auth flow therefore with the Bundle ID as the client ID, then the backend (allauth) tries to use the Service ID, it will fail with `invalid_id` because of the mismatch. If however the Bundle ID was first in the settings string, then things would work for iOS, but would fail for flows started by web (react) because web would use the Service ID, but backend would use the Bundle ID.

By what mechanism is allauth intending to cope with these 2 disparate IDs?

Maybe the identity token from the auth response should be used to derive the `sub` (subject claim) so it always matches the requesting client id, rather than just taking the first client id in the settings list?

**Comment by julianpacker** [comment] 2022-01-21 19:08
Any chance you figured anything out here?

**Comment by blablacio** [comment] 2022-05-16 09:27
For anyone still wondering: you need to have client ID for web listed first before the one for native.

Web always picks the first one, but for native all of them are checked against the `aud` field in the `id_token`.

**Comment by brychter-merix** [comment] 2022-05-16 10:56
@blablacio What do you mean "native all of them are checked against the aud field in the id_token"? We have that issue in our project but the endpoint for web and in our case react-native apps is exactly the same. After signup/login by Apple we are sending request to Django server. And always there is an error of 2 different ID's because react-native is using a different one and web different as well.

I've changed that as you suggested, Web client ID is on first place: `com.xxx.login, com.xxx`. But now works only web, and mobile is crashing :/ If I change place of these ID's mobile is working, web is crashing :D

**Comment by blablacio** [comment] 2022-05-16 11:23
Well, hard to explain why it is like that as it's hard to debug this locally, but it seems to me that the native call to the endpoint goes through `get_verified_identity_data` and `get_client_id` methods on the `AppleOAuth2Adapter`, while web call goes through `get_client_id` on the `AppleOAuth2Client`.

Don't quote me on that, that's just my gut feeling because `get_verified_identity_data` and `get_client_id` on the `AppleOAuth2Adapter` checks against all the client IDs, while `get_client_id` on the `AppleOAuth2Client` just takes the first client ID.

My current configuration:
```
SOCIALACCOUNT_PROVIDERS = {
    'apple': {
        'APP': {
            'client_id': 'com.app.web,com.app.native',
            'key': 'key',
            'secret': 'secret',
            'certificate_key': os.getenv('APPLE_LOGIN_CERTIFICATE')
        }
    }
}
```

**Comment by brychter-merix** [comment] 2022-05-16 11:29
Hmm that's very interesting. But you have created only one endpoint for both platforms, right? Because I've got same configuration basically, and this is my endpoint view for apple login, and it's not working. 

```py
class AppleLoginView(SocialLoginView):
    adapter_class = AppleOAuth2Adapter
    client_class = AppleOAuth2Client
    serializer_class = SocialLoginSerializer
```

**Comment by blablacio** [comment] 2022-05-16 11:47
I also have only one endpoint handling both web and native.

Here's the view:
```
class AppleLoginView(BaseLoginView):
    adapter_class = AppleOAuth2Adapter
    client_class = AppleOAuth2Client
    callback_url = f'https://{settings.APP_DOMAIN}/signup/'
```

I have some extra stuff on the `BaseLoginView` as well as the serializer defined there. I had to define `callback_url` though as I was getting errors without it.

**Comment by brychter-merix** [comment] 2022-05-16 14:33
Ok, so maybe the case is your custom `BaseLoginView` or Serialiser. Because on that point, all is the same, and for me, it's not working.

**Comment by blablacio** [comment] 2022-05-16 14:41
Not much going on in `BaseLoginView` -- just handling some custom data passed. It inherits from `SocialLoginView` and overrides `post` method:

```
    def post(self, request, *args, **kwargs):
        self.serializer = self.get_serializer(data=self.request.data)
        self.serializer.is_valid(raise_exception=True)

        # Login user
        self.login()

        return self.get_response()
```
as opposed to the original `SocialLoginView->LoginView:post`:
```
    def post(self, request, *args, **kwargs):
        self.request = request
        self.serializer = self.get_serializer(data=self.request.data)
        self.serializer.is_valid(raise_exception=True)

        self.login()
        return self.get_response()
```

By the way, I'm using `dj-rest-auth`, maybe that's also something worth mentioning.

**Comment by brychter-merix** [comment] 2022-05-17 04:57
Yeah, I've got `dj-rest-auth` as well. I don't know what's going on here 😄  I'm definitely missing something.

**Comment by blablacio** [comment] 2022-05-17 12:39
What is the error you're getting? Might be able to help if you post more details.

**Comment by brychter-merix** [comment] 2022-05-18 05:32
```
[OAuth2Error]
Error retrieving access token: b'{"error":"invalid_grant","error_description":"client_id mismatch. The code was not issued to com.app.test.login."}'
```
That is the situation where `com.app.test.login` is `SERVICE_ID` and I want to login via mobile app, which should use `com.app.test` ID. Both of ID's looks like this in settings:

```
com.app.test.login, com.app.test
```

Web first, mobile second.

**Comment by blablacio** [comment] 2022-05-25 14:02
Weird, still using the default client and adapter.

In any case, seems like your solution should work @yandiro.

**Comment by yandiro** [comment] 2022-05-30 23:10
There is a new issue now :man_facepalming:, users that sign in with the mobile app are not recognised by the web app. I think it may be because they are using different `client_id`s, since the web app uses a `service ID` and the mobile app uses an `App ID`. How are you dealing with this, @blablacio ? Would you mind sharing? 

Cheers!

**Comment by brychter-merix** [comment] 2022-05-31 05:12
@yandiro That's very weird behavior. I have a very similar solution to yours - custom `AppleOAuth2Client` and `AppleOAuth2Adapter`. Everything is working great now.

```py
class WebAppleOAuth2Client(AppleOAuth2Client):
    def get_client_id(self):
        return settings.APPLE_CLIENT_ID


class WebAppleOAuth2Adapter(AppleOAuth2Adapter):
    def get_client_id(self, provider):
        return settings.APPLE_CLIENT_ID
```

**Comment by yandiro** [comment] 2022-05-31 12:01
There is only one issue remaining, when the user is created using the mobile app, the name doesn't seem to come. The mobile team say they are sending the correct scope, though.

So the remaining question is, what does my SocialLoginView Class expect to receive in the request?
The mobile app is only sending this to the backend:
```
{
  "code": <authorizationCode returned by Apple>
}
``` 
Do they need to send the name too?

**Comment by brychter-merix** [comment] 2022-05-31 12:09
On the mobile app, on the request, we are including beside `code` - `idToken` which is `nonce` variable coming from Apple Native response object. But we are using React Native and `react-native-apple-authentication` package for that.

**Comment by blablacio** [comment] 2022-05-31 12:36
@yandiro and @brychter-merix I was thinking that the issue might be the data you supply from native and/or web.

So here's what we're doing:
- Using `react-apple-signin-auth` on web and passing `code` and `id_token` to backend endpoint
- Using `react-native-apple-authentication` on native and passing `access_token` (coming as `authorizationCode` from library) and `id_token` (coming as `identityToken` from library) to backend endpoint
- Only notable change we had to make is list the web client ID first before the native one (no real need for overriding client/adapter/view classes I believe)

Hope that helps you to figure it out.

**Comment by aehlke** [comment] 2023-07-16 23:55
Is the latest advice here working stably for everyone?

**Comment by JohnsonMasino** [comment] 2024-01-12 09:15
Please guys... I have a question. Must I open a membership account at apple developer site to obtain client secret and all the necessary IDs to implement apple sign-in in my django api project ? They are asking me to pay the sum of $99 to able to register a developer account. Is there a way I can override this payment ?

**Comment by aehlke** [comment] 2024-01-12 16:30
@JohnsonMasino https://developer.apple.com/support/compare-memberships/ looks like it's required. Apple is a trash monopolist company sadly.

**Comment by JohnsonMasino** [comment] 2024-01-12 16:38
[@aehlke](https://github.com/aehlke) Yes it is !
I made my research and figured I must enroll. Its fine.

**Comment by pennersr** [comment] 2024-05-05 19:11
For those using dj-rest-auth, you can work around this and configure separate apps, as follows:

    # settings.py
    SOCIALACCOUNT_PROVIDERS = {
        "apple": {
            "APPS": [
                {"client_id": "client1", ...},
                {"client_id": "client2", ...},
            ]
        }
    }
    APPLE_MOBILE_CLIENT_ID = "client1"
    APPLE_WEB_CLIENT_ID = "client2"

    # Custom Adapter
    from allauth.core import context

    class MySocialAccountAdapter(DefaultSocialAccountAdapter):
        def list_apps(self, request, provider=None, client_id=None):
            if not request:
                request = context.request
            apps = super().list_apps(request=request, provider=provider, client_id=client_id)
            if provider == "apple":
                if request.path.startswith("/api"):
                    apps = [app for app in apps if app.client_id == settings.APPLE_MOBILE_CLIENT_ID]
                else:
                    apps = [app for app in apps if not app.client_id == settings.APPLE_WEB_CLIENT_ID]
            return apps

As for using allauth headless API, the `client_id` is required to be passed to the token endpoint, so it is always clear what app is used, avoiding the need for the above workaround.

https://docs.allauth.org/en/dev/headless/openapi-specification/#tag/Authentication:-Providers/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1provider~1token/post

**Comment by pennersr** [comment] 2024-05-05 19:50
> By what mechanism is allauth intending to cope with these 2 disparate IDs?

- For `allauth.headless`,  the `client_id` is passed to the endpoint, removing any ambiguity. 
- For regular allauth, you can setup multiple apps per provider, though without the `list_apps()` workaround above, it becomes ambiguous what app to pick. This is still to be fixed.

**Comment by pennersr** [comment] 2024-05-05 21:21
Closed via 38021aea

**Closed by pennersr** 2024-05-05 21:21 UTC
Labels: Help wanted

**Comment by trackers153** [comment] 2024-08-29 18:41
> @yandiro That's very weird behavior. I have a very similar solution to yours - custom `AppleOAuth2Client` and `AppleOAuth2Adapter`. Everything is working great now.
> 
> ```python
> class WebAppleOAuth2Client(AppleOAuth2Client):
>     def get_client_id(self):
>         return settings.APPLE_CLIENT_ID
> 
> 
> class WebAppleOAuth2Adapter(AppleOAuth2Adapter):
>     def get_client_id(self, provider):
>         return settings.APPLE_CLIENT_ID
> ```
> 
> Are you sure that on developer.apple.com in Web Authentication Configuration you have selected the correct `Primary App ID`?

Hi @benrychter -- thanks for this solution. To clarify, are you setting up two different views one for mobile and one for web (diff URLs like /auth/apple/ and /auth/appleweb/) and the one for web uses the custom Client/Adapter classes? I am a bit confused as to what to do with the derived classes. Thanks.

**Comment by harm-1** [comment] 2024-12-12 14:39
@pennersr I needed some changes in your [solution](https://github.com/pennersr/django-allauth/issues/2718#issuecomment-2094916847).
So I made this:

    def list_apps(self, request, provider=None, client_id=None):
        client_id = request.POST.get('client_id')
        apps = super().list_apps(request=request, provider=provider, client_id=client_id)
        return apps

The idea is that I need to support multiple client_id's, so I would like to add the client_id in the post request, so I can filter here for the right client_id. 

The issue is just that `request.POST` is empty. And `request.body` and `request.data` are also empty. 
I don't understand how this is possible and how I can access the data from the post request I made. 

Could you help me?

**Comment by pennersr** [comment] 2026-06-11 17:04
https://codeberg.org/allauth/django-allauth/issues/2718
