### ISSUE TITLE
Ideomatics way to change styles for form

### ISSUE THREAD

**Issue by lk-geimfari** [pennersr/django-allauth#2009] opened 2018-04-17 15:57 UTC
What is a correct way to update styles for the override form styles? I mean, how can i correctly use my custom styles for form. 

Example:

```html
<form class="login" method="POST" action="{% url 'account_login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
</form>
```

But I want to use my customs form with my custom inputs, how can I do it correctly? How do you do such things?

P.S I have tried a lot of cases from StackOverFlow, but all of them does not work correctly.

**Comment by pennersr** [comment] 2018-05-21 15:19
There are quite some third party Django apps that allow you to control the form rendering from within the templates. Closing this -- this is not an issue in allauth.

**Closed by pennersr** 2018-05-21 15:19 UTC

**Comment by stealth-d** [comment] 2023-10-09 01:15
the issue is that your documentation sucks :D

**Comment by pennersr** [comment] 2026-06-10 20:49
https://codeberg.org/allauth/django-allauth/issues/2009
