### ISSUE TITLE
Unable to treat password resets as email verification confirmations

### ISSUE THREAD

**Issue by immanuelnoel** [pennersr/django-allauth#2084] opened 2018-08-18 08:56 UTC
I'm using users to login into their auto-created accounts. They need to do a password reset since they are not provided with a password - the templates are worded accordingly. 

Now, since ACCOUNT_EMAIL_VERIFICATION is set to "mandatory", they get an email right after the password reset. I'm unable to double up password reset, as a email verification step. 

I'm thinking of listening for the signal, allauth.account.signals.password_reset(request, user), and calling - confirm_email(self, request, email_address). 

Is this the only way, or am I missing a configuration.

**Comment by derek-adair** [comment] 2023-09-12 12:07
@rokstrnisa it is courteous to close issues like this if you come to a resolution <3.  Thank you for your proactive solution I will likely be adding it to the docs as an example.

@pennersr close as not planned.  The user demonstrated a very simple and straightforward solution that doesn't require modifying allauth.

**Comment by pennersr** [comment] 2023-09-12 18:30
The password reset token does not store the email the password reset was sent to, meaning, you don't know what email address should be verified. Even in case of just 1 email address, there is no guarantee that that email address is the same as the one the reset was sent to if the user changes the email after sending the reset email. Therefore, this is a valid issue that needs a design decision -- whether or not to store the email (id) in the token.

**Comment by pennersr** [comment] 2023-12-16 12:34
Dupe of #1267

**Closed by pennersr** 2023-12-16 12:34 UTC
Labels: Design Decision Needed

**Comment by pennersr** [comment] 2026-06-10 20:51
https://codeberg.org/allauth/django-allauth/issues/2084
