### ISSUE TITLE
GUID as primarty key for SocialAccount model

### ISSUE THREAD

**Issue by Akay7** [pennersr/django-allauth#2429] opened 2020-01-02 06:08 UTC
It will nice to have the opportunity to set GUID as the primary key for the SocialAccount model to preventing disclosure quantity of accounts inside the application. 
It's possible to make the same with the user account in Django by settings custom model with GUID as PK to AUTH_USER_MODEL in settings.

**Comment by derek-adair** [comment] 2023-08-30 16:48
Close as a discussion;

But yes, you can write whatever custom user models you want or need -- you will just have to write your own adapters, forms, etc.

**Comment by pennersr** [comment] 2023-08-30 18:44
No, the request here is to change the primary key of the social account model. That cannot be done by writing custom user models, and is therefore a valid request. Same goes for the `EmailAddress` model.  So, basically you would want to swap out those models, or, perhaps at least be able to alter the PK field. 

Though, we already have a very related issue for that open #1318 ... so let's close this as a dupe of that.

**Closed by pennersr** 2023-08-30 18:44 UTC

**Comment by Akay7** [comment] 2023-12-20 03:38
Seems that after [those changes](https://github.com/Akay7/django-allauth/commit/32c9eaf2d70cfae4f52f8e51b0ac4cd1523c5915)  it will be possible to set UUID as PK with `ALLAUTH_DEFAULT_AUTO_FIELD` setting. Thanks @pennersr !

**Comment by pennersr** [comment] 2026-06-10 20:59
https://codeberg.org/allauth/django-allauth/issues/2429
