### ISSUE TITLE
Migrations, dependencies and 'relation "auth_user" does not exist' vs 'relation "django_site" does not exist'

### ISSUE THREAD

**Issue by tobiasprinz** [pennersr/django-allauth#1232] opened 2015-12-17 11:20 UTC
Hi,
I am pretty sure this is not your fault, but I have failed so far to understand the issue: I am running a system with python 2.7.10 and django 1.8.6 or .7.

 I am obviously not a django expert, so I am just guessing from other frameworks. Anyway:

Whenever I start my migrations from scratch, both ```python manage.py syncdb``` or ```python manage.py migrate``` fail with ```relation "auth_user" does not exist```. Sounds to my like whatever other app has a dependency on your provider.

But when I ```python manage.py migrate auth``` first, I run into ```relation "django_site" does not exist``` after migration ```auth.0006_require_contenttypes_0002```.  That, on the other hand, does sound like a problem with this lib.

I found several threads on stackoverflow regarding this, and running the specific auth migration until it fails and then the normal one helps. But that's a hack and does not work for tests which drop the database. So can you tell me why this happens and whether there is a way to correct the migration execution order? The order in INSTALLED_APPS does not seem to influence this.

**Comment by aaugustin** [comment] 2016-01-13 18:06
Do you have `django.contrib.sites` in INSTALLED_APPS?

**Comment by pennersr** [comment] 2016-01-26 21:10
I am not sure what the issue is, but this is likely due to your project setup and not some issue in allauth. Therefore I am closing this issue...

**Closed by pennersr** 2016-01-26 21:10 UTC

**Comment by cansin** [comment] 2022-02-22 00:06
Fwiw, I am hitting the exact same error on a repo I work these days. Once I figure out what the problem I will report back.

**Comment by pennersr** [comment] 2026-06-10 19:48
https://codeberg.org/allauth/django-allauth/issues/1232
