### ISSUE TITLE
Social network login failure happened sometimes, sometimes don't 

### ISSUE THREAD

**Issue by Zorig** [pennersr/django-allauth#1566] opened 2016-12-18 07:41 UTC
hi i am using `django-allauth (0.28.0)` + `django(1.9.8)` and configured only facebook according to docs. But when i try to login it gives me **Social network login failure** sometimes. Also sometimes it gives **connection refused error** here is my configuration 
```
# SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
        'facebook': {
            'METHOD': 'oauth2',
            'SCOPE': ['email', 'public_profile', 'user_friends'],
            'FIELDS': [
                'id',
                'email',
                'name',
                'first_name',
                'last_name',
                'verified',
                'locale',
                'timezone',
                'link',
                'gender',
                'updated_time'],
            'VERIFIED_EMAIL': False,
        }
    }
```

on facebook redirect URI is this below. Also i tried `http://mydomain/` too it gives same result.
![screenshot-developers facebook com-2016-12-18-15-37-41](https://cloud.githubusercontent.com/assets/1277672/21292221/2e3b8b02-c538-11e6-89d6-9395e96f8ac2.png)

Can anyone help me to solve this?

**Comment by hongquan** [comment] 2016-12-19 18:30
There may be DNS error in your server.

**Comment by pennersr** [comment] 2017-02-02 18:45
Sorry, I will have to close this one as allauth is unlikely to be the cause here...

**Closed by pennersr** 2017-02-02 18:45 UTC

**Comment by pennersr** [comment] 2026-06-10 19:57
https://codeberg.org/allauth/django-allauth/issues/1566
