### ISSUE TITLE
Postgres Native JSONField

### ISSUE THREAD

**Issue by JayTurnr** [pennersr/django-allauth#2083] opened 2018-08-16 03:29 UTC
https://github.com/pennersr/django-allauth/blob/9c31b6576628e9d6971349abc189dfd613d6591e/allauth/socialaccount/models.py#L102

If it possible to make this use Postgres native JSONField if the user is on Postgres?
https://docs.djangoproject.com/en/2.1/ref/contrib/postgres/fields/#jsonfield

**Comment by jleclanche** [comment] 2018-10-04 02:35
Dupe of #598.

**Closed** 2018-10-04 08:02 UTC

**Comment by pennersr** [comment] 2026-06-10 20:51
https://codeberg.org/allauth/django-allauth/issues/2083
