### ISSUE TITLE
Password reset leaks membership

### ISSUE THREAD

**Issue by StuartMacKay** [pennersr/django-allauth#2712] opened 2020-11-10 19:34 UTC
Say I have a web site for a super secret society. Somebody with a list of emails can use the password reset form to determine who is a member. Instead of raising a validation error when an unregistered email address is entered the password reset form should do nothing or display a message to the effect that is the email address is registered then a reset link will have been sent.

**Comment by 9mido** [comment] 2020-11-10 19:52
@StuartMacKay Seems related to issue 1307.

**Comment by pennersr** [comment] 2020-11-10 20:01
Duplicate of #1307

**Closed by pennersr** 2020-11-10 20:01 UTC

**Comment by pennersr** [comment] 2026-06-11 17:04
https://codeberg.org/allauth/django-allauth/issues/2712
