### ISSUE TITLE
ImproperlyConfigured at /accounts/login/

### ISSUE THREAD

**Issue by macbotxxx** [pennersr/django-allauth#2981] opened 2021-11-19 15:49 UTC
after working on my settings.py which works perfectly fine on localhost but shows this on production ImproperlyConfigured at /accounts/login/ ...

AUTH_USER_MODEL = "users.User"
LOGIN_REDIRECT_URL = "user_dashboard"
LOGIN_URL = "account_login"
SITE_ID = 1

# django-allauth
# ------------------------------------------------------------------------------
ACCOUNT_ALLOW_REGISTRATION = env.bool("DJANGO_ACCOUNT_ALLOW_REGISTRATION", True)

ACCOUNT_AUTHENTICATION_METHOD = "email"

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_LOGIN_ATTEMPTS_LIMIT = 3
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 86400
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_EMAIL_VERIFICATION = "optional"

ACCOUNT_ADAPTER = "next.users.adapters.AccountAdapter"

**Comment by 9mido** [comment] 2021-11-20 00:09
Need more information. Show us a traceback from the terminal and tell us what production servers/company you are using for your website. What code is your ACCOUNT_ADAPTER referencing? Where does ACCOUNT_ALLOW_REGISTRATION come from? 

Look at https://django-allauth.readthedocs.io/en/latest/configuration.html

**Comment by macbotxxx** [comment] 2021-11-20 02:42
adapters.py

from typing import Any

from allauth.account.adapter import DefaultAccountAdapter
from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.conf import settings
from django.http import HttpRequest


class AccountAdapter(DefaultAccountAdapter):
    def is_open_for_signup(self, request: HttpRequest):
        return getattr(settings, "ACCOUNT_ALLOW_REGISTRATION", True)


class SocialAccountAdapter(DefaultSocialAccountAdapter):
    def is_open_for_signup(self, request: HttpRequest, sociallogin: Any):
        return getattr(settings, "ACCOUNT_ALLOW_REGISTRATION", True)

**Comment by pennersr** [comment] 2021-11-24 18:24
Closing -- this is unlikely to be caused by a bug in allauth.

**Closed by pennersr** 2021-11-24 18:24 UTC

**Comment by pennersr** [comment] 2026-06-11 17:11
https://codeberg.org/allauth/django-allauth/issues/2981
