### ISSUE TITLE
Confirmation email with short code verification

### ISSUE THREAD

**Issue by MySecondLanguage** [pennersr/django-allauth#2814] opened 2021-03-23 08:59 UTC
I have read all the allauth documentation and i have not found any docs related to short code based email verification. 

Currently my mail confirmation is working like that way when user signup, it receives a link, and when user click on link, it gets verified, but i want to implement in mobile application so i dont to let the user to go ouside of application for verification.

So i need to send a short number like 12345 to user mail so that they can verify their mail with the short number.

is it possible with django-allauth?

**Comment by 9mido** [comment] 2021-03-23 20:22
You can do something like this with OTP:

https://medium.com/@vasufauzan786/user-registration-and-verification-using-otp-in-django-without-use-of-any-fancy-django-utilities-7ce82161b25d

With this, it seems possible. But not sure how to do it where it does not go outside of the application for verification. Maybe you could generate the OTP code in your template itself instead of going outside of it with an email application. 

If you figure it out, please reply with your code solution to help others or make a PR.

**Comment by pennersr** [comment] 2021-12-17 10:17
Dupe of #2061

**Closed by pennersr** 2021-12-17 10:17 UTC

**Comment by pennersr** [comment] 2026-06-11 17:06
https://codeberg.org/allauth/django-allauth/issues/2814
