### ISSUE TITLE
templates not adequately namespaced

### ISSUE THREAD

**Issue by catskul** [pennersr/django-allauth#940] opened 2015-05-05 16:59 UTC
base.html conflicts with other packages who similarly have not namespaced their templates.

This cause all kinds of hard to diagnose problems.

As recommended by the Django docs, templates should be pushed one level deeper below a parent directory named for the app parent.

**Comment by pennersr** [comment] 2015-07-26 15:16
Dupe of #370

**Closed by pennersr** 2015-07-26 15:16 UTC

**Comment by pennersr** [comment] 2026-06-10 19:41
https://codeberg.org/allauth/django-allauth/issues/940
