### ISSUE TITLE
Get user in get_email_confirmation_redirect_url when no authenticated

### ISSUE THREAD

**Issue by abrange** [pennersr/django-allauth#1932] opened 2018-01-21 05:44 UTC
I am trying to redirect a user to a specific URL based on the user, but I can't find a way to know which is the user or email within

`def get_email_confirmation_redirect_url(self, request)`

that just has confirmed their email in order to prepare the URL.

As additional information, my complete flow is:
1) User signup using only email.
2) User clicks on confirmation link from their email.
3) User click on "confirm email" button.
4) Now, I would like to show a set password form (with a Name field too).

In (3), I using get_email_confirmation_redirect_url to get the URL used by SetPassword, so it could be the next page shown.

Edit:
I have figure out a way to get the user, it's working but not sure if its the best way.:
1) get key in URL and 2) get the user using _EmailConfirmationHMAC.from_key_

```
            key_ = re.match(r"/accounts/confirm-email/(.+)/.*", request.path).group(1)
            user = EmailConfirmationHMAC.from_key(key_).email_address.user

```

Thanks,
Alvaro

**Comment by SiddharthPant** [comment] 2019-09-26 19:39
Instead of depending on regex match you can directly use `request.resolver_match.kwargs['key']`

**Comment by pennersr** [comment] 2023-08-31 18:44
It would definitely make sense to pass along the email that is being confirmed to `get_email_confirmation_redirect_url()`. Though, that is a backwards incompatible change to the adapter.

**Comment by derek-adair** [comment] 2023-08-31 20:18
can that not be looked up in the request object?

**Comment by pennersr** [comment] 2023-09-01 07:50
Not without resorting to hacks like duplicating the lookups that allauth already did.

**Comment by pennersr** [comment] 2024-05-05 14:43
Fixed in 0c95626d -- there now is:

```get_email_verification_redirect_url(self, email_address)```

**Closed by pennersr** 2024-05-05 14:43 UTC

**Comment by jayqi** [comment] 2024-09-03 23:21
Hi @pennersr,

I'm looking at upgrading allauth from an old version for an application with a custom adapter implementing `get_email_confirmation_redirect_url` to a newer version that has `get_email_verification_redirect_url` (and says the old method is deprecated). 

In our existing code, we are following code examples discussed in https://github.com/pennersr/django-allauth/issues/1555 for getting the redirect URL from the passed-in request's session. This URL had been stashed in the session when the user went through the signup view, so that we could attempt to return them to whatever page they were on before.

Since `request` is no longer passed into `get_email_verification_redirect_url`, can you please help explain the intended way to accomplish something like this? I haven't been able to find any documentation that covers this. Thanks!

**Comment by pennersr** [comment] 2024-09-04 05:42
@jayqi You can use `self.request` in adapter methods.

**Comment by pennersr** [comment] 2026-06-10 20:47
https://codeberg.org/allauth/django-allauth/issues/1932
