### ISSUE TITLE
Issue with sign in via Google. 

### ISSUE THREAD

**Issue by NikhilKamathB** [pennersr/django-allauth#3124] opened 2022-07-07 15:44 UTC
Hi,

I am using dj_rest_auth along with django_allauth to log in with Google. I have followed the documentation provided for both packages to achieve a social account login. To get things set up, OAuth and credentials in the Google cloud console are also set correctly (with appropriate Authorized JavaScript origins and Authorized redirect URIs). Also, [this section of the FAQ](https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue) seems to be addressed.

The problem that I'm facing is while logging in using Google OAuth. Please note that this is happening only with the API Views. Template-driven login seems to be working smoothly.

I am facing this issue after trying out the following steps:

- As mentioned [here](https://dj-rest-auth.readthedocs.io/en/latest/installation.html#google), I am hitting `https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=<CALLBACK_URL_YOU_SET_ON_GOOGLE>&prompt=consent&response_type=code&client_id=<YOUR CLIENT ID>&scope=openid%20email%20profile&access_type=offline` this endpoint to get the "code". Well, this redirects me to the page (see below) that lists Google accounts.
![G1](https://user-images.githubusercontent.com/55628827/177805831-f2a25388-8ef8-4322-bf64-c68f942eac9e.png)

- After selecting an account, it displays a page that states "Social Network Login Failure".
![G2](https://user-images.githubusercontent.com/55628827/177806461-8e31c1b6-f3d3-48ff-a9aa-15ef0a556ff1.png)

- When it comes to the API calls, if I send `{"code": <CODE>}` to Google auth login url defined by django_allauth I get `"Error retrieving access token: b'{\\n  \"error\": \"invalid_grant\",\\n  \"error_description\": \"Bad Request\"\\n}'"` error.

Again, please note that this error is not faced with Template-based login.

On further digging, I realized that the issue lies in `allauth.socialaccount.providers.oauth2.client.OAuth2Client`, 
`resp = requests.request(
            self.access_token_method,
            url,
            params=params,
            data=data,
            headers=self.headers,
            auth=auth,
        )`
Here, resp.status_code was 400 due to which the access_token is None and thus the error.

Please help me resolve this issue. Many thanks for considering my request.

**Comment by hamza-hadda** [comment] 2022-08-06 03:27
I have the same issue did you find any solution for that?

**Comment by JOY-SAM** [comment] 2022-08-18 18:30
Same here bro searching for months

**Comment by NikhilKamathB** [comment] 2022-08-18 19:10
@hamza-hadda and @JOY-SAM, as mentioned earlier, Google OAuth seems to be working fine for template-based login. For  API-based views, I followed these (below) steps to over come this issue. This is not a solution just a work-around.

- Setup everything needed for Google OAuth to work.
- While testing on local machine, stop the Django server and hit  ```https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=<CALLBACK_URL_YOU_SET_ON_GOOGLE>&prompt=consent&response_type=code&client_id=<YOUR CLIENT ID>&scope=openid%20email%20profile&access_type=offline```.
- On selecting a profile and successful authentication, you will be redirected to a page stating "connection failed" (because the Django server is down).
- Copy the 'code' parameter in the URL and start the Django server.
- Hit the Google Login API (swagger / postman) (Note that the 'code' parameter value must be passed with this API - POST request).

These steps allowed me to test Google OAuth locally. When it comes to production, the 'code' or equivalent parameter is shared with the Django server.

**Comment by modbender** [comment] 2023-03-18 16:29
@pennersr Need update on this, same error for me:

On django its: Bad Request: /api/social/login/google/

On frontend it says (I'm using nuxt-auth port of NextAuth:
[next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR]
https://next-auth.js.org/errors#oauth_callback_handler_error JWT Claims Set MUST be an object {
  message: 'JWT Claims Set MUST be an object',
  stack: 'TypeError: JWT Claims Set MUST be an object\n' +
    '    at new ProduceJWT (E:\\Project\\site-js\\node_modules\\jose\\dist\\node\\cjs\\jwt\\produce.js:10:19)\n' +
    '    at new EncryptJWT (E:\\Project\\site-js\\node_modules\\jose\\dist\\node\\cjs\\jwt\\encrypt.js:7:1)\n' +
    '    at Object.encode (E:\\Project\\site-js\\node_modules\\next-auth\\jwt\\index.js:49:16)\n' +
    '    at async Object.callback (E:\\Project\\site-js\\node_modules\\next-auth\\core\\routes\\callback.js:142:28)\n' +       
    '    at async AuthHandler (E:\\Project\\site-js\\node_modules\\next-auth\\core\\index.js:201:28)\n' +
    '    at async file:///E:/Project/site-js/.nuxt/dev/index.mjs:548:24\n' +
    '    at async Object.handler (file:///E:/Project/site-js/node_modules/h3/dist/index.mjs:1212:19)\n' +
    '    at async Server.toNodeHandle (file:///E:/Project/site-js/node_modules/h3/dist/index.mjs:1287:7)',
  name: 'TypeError'

**Comment by pennersr** [comment] 2023-07-05 20:38
Closing -- this uses a combination of allauth and dj-rest-auth and it is not obvious that allauth is the cause.

**Closed by pennersr** 2023-07-05 20:38 UTC

**Comment by pennersr** [comment] 2026-06-11 17:15
https://codeberg.org/allauth/django-allauth/issues/3124
