### ISSUE TITLE
OpenID Installation issue

### ISSUE THREAD

**Issue by stuck1233333** [pennersr/django-allauth#2351] opened 2019-08-29 20:27 UTC
Under settings.py, if I add 'allauth.socialaccount.providers.openid' to INSTALLED_APPS,
I get the following error: 

ModuleNotFoundError: No module named 'allauth.socialaccount.providers.openidcorsheaders'

Any recommendations?
Thanks!

**Comment by pennersr** [comment] 2019-12-14 11:25
Likely you are missing a comma in your settings somewhere. Closing, not a bug in allauth.

**Closed by pennersr** 2019-12-14 11:25 UTC

**Comment by pennersr** [comment] 2026-06-10 20:57
https://codeberg.org/allauth/django-allauth/issues/2351
