### ISSUE TITLE
RemovedInDjango40Warning: The providing_args argument is deprecated.

### ISSUE THREAD

**Issue by snowman2** [pennersr/django-allauth#2679] opened 2020-10-09 16:22 UTC
Recently noticed this:
```
allauth/account/signals.py:5: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
    user_logged_in = Signal(providing_args=["request", "user"])
```

**Comment by pennersr** [comment] 2020-10-09 19:25
Dupe of #2678

**Closed by pennersr** 2020-10-09 19:25 UTC

**Comment by pennersr** [comment] 2026-06-11 17:03
https://codeberg.org/allauth/django-allauth/issues/2679
