### ISSUE TITLE
Error in email confirmation with LOGIN_ON_EMAIL_CONFIRMATION = True

### ISSUE THREAD

**Issue by SurajPysquad** [pennersr/django-allauth#3452] opened 2023-09-27 10:14 UTC
```<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">SessionInterrupted at /accounts/confirm-email/MTc4:1qlRWn:pNv2nphV_zYWAEYNm5EAGxI9_wQLtk85rgKZLU4V67Q/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.</pre>

Request Method: | POST
-- | --
http://127.0.0.1:8000/accounts/confirm-email/MTc4:1qlRWn:pNv2nphV_zYWAEYNm5EAGxI9_wQLtk85rgKZLU4V67Q/
4.2.2
SessionInterrupted
The request's session was deleted before the request completed. The user may have logged out in a concurrent request, for example.
/home/pys/suraj_workplace/virtualenv/captain_env/lib/python3.10/site-packages/django/contrib/sessions/middleware.py, line 61, in process_response
allauth.account.views.ConfirmEmailView
/home/pys/suraj_workplace/virtualenv/captain_env/bin/python
3.10.12

```

**Comment by pennersr** [comment] 2023-09-29 10:58
I doubt that this is caused by an issue in allauth. In any case, without a clear way of reproducing this I need to close this.

**Closed by pennersr** 2023-09-29 10:58 UTC

**Comment by pennersr** [comment] 2026-06-12 10:22
https://codeberg.org/allauth/django-allauth/issues/3452
