### ISSUE TITLE
Deprecated use of `webauthn_json_mapping`

### ISSUE THREAD

**Issue by jmsmkn** [pennersr/django-allauth#4002] opened 2024-08-01 14:50 UTC
Since upgrading to version 64.0.0 a new warning has appeared in our tests due to django-allauth now using fido2:

```
 allauth/account/tests/test_adapter.py::test_adapter_pre_login
    /home/runner/work/django-allauth/django-allauth/.tox/prjregular-py311-djangomain/lib/python3.11/site-packages/fido2/features.py:66: DeprecationWarning: Deprecated use of webauthn_json_mapping.

    You are using deprecated functionality which will change in the next major version of
    python-fido2. You can opt-in to use the new functionality now by adding the following
    to your code somewhere where it gets executed prior to using the affected functionality:
    
      import fido2.features
      fido2.features.webauthn_json_mapping.enabled = True
    
    To silence this warning but retain the current behavior, instead set enabled to False:
      fido2.features.webauthn_json_mapping.enabled = False
    
    JSON values for WebAuthn data class Mapping interface.
    
    This changes the keys and values used by the webauthn data classes when accessed using
    the Mapping (dict) interface (eg. user_entity["id"] and the from_dict() methods) to be
    JSON-friendly and align with the current draft of the next WebAuthn Level specification.
    For the most part, this means that binary values (bytes) are represented as URL-safe
    base64 encoded strings instead.
```

This also appears in the logs of the latest CI tests here. I would have made a PR but I don't know enough about the consequences of making such a change.

**Comment by pennersr** [comment] 2024-08-01 16:31
That warning seems to be caused by this `if` statement:

``` python
if not fido2.features.webauthn_json_mapping.enabled:
    fido2.features.webauthn_json_mapping.enabled = True
```

So, we're already opted in to the new behavior, but at the time the condition is evaluated enabled is not set yet.

**Comment by ryanhiebert** [comment] 2024-08-03 14:13
@pennersr I'm curious why you chose `fido2` instead of [`webauthn`](https://pypi.org/project/webauthn/). Little annoyances like this one and not allowing localhost domains as secure contexts bugged me with fido2, so I've been eyeing using webauthn instead. Did you find challenges with that library?

**Comment by pennersr** [comment] 2024-08-03 14:29
@ryanhiebert I wanted something battle tested, e.g. Sentry is using `fido2` as well. Note that I am not implying `webauthn` has issues, though this looked a bit uneasy: https://github.com/duo-labs/py_webauthn/issues/91 

 In the end, the choice between `fido2` or `webauthn` is just an implementation detail, and should one option clearly prevail above the other then internals can always be replaced without any impact on the outside.

**Comment by ryanhiebert** [comment] 2024-08-03 15:16
Fair enough. I'm not sure if I'd seen that issue or not, although the response I'd seen from the maintainers of fido2 about using localhost as a secure context was off-putting to me: https://github.com/Yubico/python-fido2/issues/122

That said, it looks like that was fixed in main, just not released yet, which I'm guessing you know about already since you mentioned the exact latest version where the setting is necessary. https://github.com/Yubico/python-fido2/pull/218

So a new release from fido2 should solve that particular complaint (although it still doesn't catch the case of `*.localhost` domains. I'll see about submitting a patch to fido2 for that).

For this one, do we need to have the `if` conditional, or can we just always set it? Would that avoid the warning?

**Comment by pennersr** [comment] 2024-08-03 17:12
Fixed via 81bbed7c

**Closed by pennersr** 2024-08-03 17:12 UTC

**Comment by lionelwust** [comment] 2025-06-26 10:31
@pennersr It seems that the line

`#/mfa/webauthn/internal/auth.py
fido2.features.webauthn_json_mapping.enabled = True
`

is causing server crash and must be removed.

**Comment by dwasyl** [comment] 2025-07-29 00:43
@lionelwust Did you find a workaround for this (without just editing the file)?

**Comment by oerd** [comment] 2025-09-28 15:36
@dwasyl  I believe `65.8.1` solves this.

**Comment by pennersr** [comment] 2026-06-12 10:34
https://codeberg.org/allauth/django-allauth/issues/4002
