### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by TobitRE** [pennersr/django-allauth#1065] opened 2015-07-29 14:02 UTC
Hy guys,

i use allauth with Facebook and it works very well.

Now i try to add twitch and i can't get it to work i get everytime only the error that something with the social-network was not working.

How can i get a more detail error?
I found no logs.

Thanks a lot

Tobit

**Comment by mxscho** [comment] 2015-07-29 22:41
I'm also currently using the Twitch OAuth2 feature of this library.
I encountered this issue myself in two different situations (which might help you to find the problem):
* As I understood, Twitch does only allow a restricted amount of requests per user if the client_id is not sent with each request (which does not happen at the moment, see also: https://github.com/pennersr/django-allauth/issues/1052).
* I also found out that sometimes the route to /[auth]/twitch/login/ (which I think returns a 302 redirect view) creates a weird redirect location/URL with scopes being passed multiple times. Like e.g.: https://api.twitch.tv/kraken/oauth2/authorize?redirect_uri=[redirect_uri]&scope=user_read+user_subscriptions+user_read+user_subscriptions+user_read+user_subscriptions+[...]&client_id=[client_id]&state=[state]&response_type=code
Whereas my settings file looked normal like this:
```python
SOCIALACCOUNT_PROVIDERS = {
	'twitch': {
		'SCOPE': [ 'user_read', 'user_subscriptions' ]
	},
}
```
Unfortunately I haven't been able to reproduce this issue/bug (?) yet and sometimes it's gone just after restarting the web server.
I think what Twitch does is that it reacts with a 500 internal server error or something like that which causes the error page.

**Comment by TobitRE** [comment] 2015-07-30 05:48
Hi mxscho,

thanks for your answer.
I also have seen this url with multiple scopes :/

So i have a random chance that twitch is working, this are bad news.

Can i log something more about this problem?
The return error from twitch would be helpful.

**Comment by mxscho** [comment] 2015-07-30 06:40
Concerning this I haven't read anything in the Twitch API documentation.
However - the URL with the multiple scopes should clearly be the cause of the problem imho.
If i've seen it correctly, the URL is generated here:
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/oauth2/client.py#L29
I cannot see anything wrong though.
The list of scopes from the settings is joined (```' '.join(...)```) and then formatted into the URL with the old % string format syntax.
It's weird because this issue is only occuring sometimes and server restarts make it disappear again.
I'm using Python 3.4 by the way - can that be a problem in any ways?

**Comment by TobitRE** [comment] 2015-07-30 08:00
ok,...

i think a problem is that i can't log all steps :( Any Idea?
Also the twitch api say the url for the app shout without https:// if i try this in the backend i get an error
https://github.com/justintv/Twitch-API/blob/master/authentication.md (Point 2)

I use python 2.7 i think this is not the problem.

**Comment by strange** [comment] 2015-08-24 12:46
We're experiencing the same issue here. It can work fine for days and then we get a slew of complaints about Twitch-login not working. All other providers seem to work fine. We've been whitelisted by Twitch so that's not the issue here.

I will look at it more closely if I can find a few minutes somewhere.

**Comment by mxscho** [comment] 2015-08-25 23:04
Would be nice to hear if this provided fix actually helps you.

**Comment by pennersr** [comment] 2016-03-11 18:35
Scope duplicates are now prevented in allauth (see 77310ea). As for the other issues reported ("works for days -- then starts failing"), I am afraid this is not under my control. Closing ...

**Closed by pennersr** 2016-03-11 18:35 UTC

**Comment by pennersr** [comment] 2026-06-10 19:44
https://codeberg.org/allauth/django-allauth/issues/1065
