### ISSUE TITLE
Confirm Email With Code

### ISSUE THREAD

**Issue by ethanitovitch** [pennersr/django-allauth#3542] opened 2023-11-30 12:11 UTC
Looks like certain email servers are disabling the signup link sent in emails (still a theory trying to confirm but haven't been able to reproduce)
Think it might be worthwhile to build a configuration for sending a code to confirm an email

**Comment by pennersr** [comment] 2023-11-30 20:03
Duplicate of #3014

**Closed by pennersr** 2023-11-30 20:03 UTC

**Comment by pennersr** [comment] 2026-06-12 10:25
https://codeberg.org/allauth/django-allauth/issues/3542
