### ISSUE TITLE
django allauth Login with google without verification after registration

### ISSUE THREAD

**Issue by kish38** [pennersr/django-allauth#2048] opened 2018-06-19 12:09 UTC
I am using django-allauth and below is the scenario.

- In the registration form email, username, pwd is given for registrations and email verification is sent.
- Now without clicking on the confirmation link in mail I am using login with google in my login page.
- It's redirected to login to google after that I landed up on page with form saying **You are about to use your Google account to login and as a final step enter username**. But I already registered with username.

If I use signup with google without registering it's working fine without confirmation mail also.
So is it not possible to login with google without verification if I used normal registration?

**Comment by derek-adair** [comment] 2023-08-19 11:16
Hmmm really wish we had an issue template for when @kish38 submitted this.  It would be very valuable to know exactly what settings he's using and what he is expecting to happen.

I THINK he is saying that with ACCOUNT_EMAIL_VERIFICATION=mandatory...

1. User registers and DOES NOT confirm email
2. Click login with google and log in w/ that social account that belongs to the email
3. User is prompted to create a new account

----------------------

 I haven't confirmed this yet but it seems legit -- i dont use social auth on my apps right now.  Quite frankly this is a pretty nasty UX problem... even if it is pretty specific.  I also have no clear cut suggestions for what to do when a user is in this state.

options;
1. Detect duplicate emails / offer to re-send verification?
2. Detect dup emails and ask to login for association?

**Comment by derek-adair** [comment] 2023-08-19 11:18
I resonate with this type of bug because my ADHD riddled brain is likely to repeat this scenario and if I were given this UX i would not complete signup.

**Comment by pennersr** [comment] 2023-08-19 11:30
I think that the report is about a local user account with email foo@gmail.com. Then, a Google login comes along with foo@gmail.com as well. Now, that results in a new signup as the local user account does not have any social accounts attached. So, rightly so, a signup form is presented and the user needs to enter a user name (we're signing up after all). 

If you dislike this behavior, you can use the new `SOCIALACCOUNT_EMAIL_AUTHENTICATION` flow part of 0.55.0.  Closing, as this new flow addresses this issue.

**Closed by pennersr** 2023-08-19 11:30 UTC

**Comment by derek-adair** [comment] 2023-08-19 12:16
Sorry if some of these triage's don't make sense or are irrelevant my knowledge of allauth is mostly outdated.  I'll be diving in to the code more in the coming weeks.

**Comment by derek-adair** [comment] 2023-08-19 12:24
If i set up a discord server for you would you care to link it?  It would clear up some noise from the issue tracker for meta discussions like this.

**Comment by derek-adair** [comment] 2023-08-19 12:26
also i'm all in on helping you here buddy.  I've been using your code for _every single django app_ i've made in the last decade.  This code is a cornerstone of django and the community would be pretty screwed w/o it.

**Comment by pennersr** [comment] 2023-08-19 17:37
@derek-adair You're free to set that up, I can link to it from here: https://django-allauth.readthedocs.io/en/latest/faq.html#this-information-is-nice-and-all-but-i-need-more -- I wouldn't want to promote a proprietary platform like Discord in a more official manner though.

**Comment by derek-adair** [comment] 2023-08-22 10:16
Oh interesting, what are your reason behind disliking discord besides it not being open source do you have?  Would you be interested in selecting some FOSS alternative? I would feel comfortable hosting it as long as it's not too expensive.

**Comment by pennersr** [comment] 2026-06-10 20:50
https://codeberg.org/allauth/django-allauth/issues/2048
