### ISSUE TITLE
Facebook auth doesn't collect enough data

### ISSUE THREAD

**Issue by richardcornish** [pennersr/django-allauth#1061] opened 2015-07-28 05:39 UTC
Facebook flow doesn't collect more than `{"name": "<name>", "id": "<user id>"}` in extra data. My settings:

```
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': [
            'email',
            'public_profile',
            'user_friends'
        ],
        'AUTH_PARAMS': {
            'auth_type': 'reauthenticate'
        },
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': lambda request: 'en_US',
        'VERIFIED_EMAIL': True,
        'VERSION': 'v2.4'
    }
}
```

More info: http://stackoverflow.com/questions/31665692/how-to-populate-social-account-instance-with-facebook-data-in-django-allauth

**Comment by pennersr** [comment] 2015-07-28 06:02
You are using 0.22.0 right? Then this is probably a duplicate of #1059   Otherwise, upgrade to 0.22.0.

**Closed by pennersr** 2015-07-28 06:02 UTC

**Comment by richardcornish** [comment] 2015-07-28 16:49
Yep, this was it! Thank you for your the quick reply and hard work on this project.

Upon close inspection, I don't think this is the same issue as #1059. I'll comment there.

**Comment by saleem1992** [comment] 2015-11-02 05:36
I am using 0.23, and yet I am not able to see anything other than "name" and "id"

**Comment by pennersr** [comment] 2026-06-10 19:44
https://codeberg.org/allauth/django-allauth/issues/1061
