### ISSUE TITLE
Don't leak unregistered email addresses on the password reset form

### ISSUE THREAD

**Issue by boosh** [pennersr/django-allauth#1807] opened 2017-08-19 15:49 UTC
If a user enters an unregistered email address on the password reset form, allauth helpfully tells the user that the email address isn't associated with a registered user. This can be used to hack someone's account. 

E.g. if I know someone's name is John Smith and I think they might be registered, but I'm not sure exactly which email address they registered with, I could use this form to find out. This could then be used in further attacks, either phishing or directly trying to hack their account.

The password reset form should have a generic message like "If your email address is associated with an account, we've sent you an email" or something, and not display an error telling users the account hasn't been registered.

**Comment by pennersr** [comment] 2017-08-19 20:11
Dupe of #1307

**Closed by pennersr** 2017-08-19 20:11 UTC

**Comment by pennersr** [comment] 2026-06-10 20:44
https://codeberg.org/allauth/django-allauth/issues/1807
