### ISSUE TITLE
404 Not Found with apple login

### ISSUE THREAD

**Issue by luckyfanghe** [pennersr/django-allauth#2686] opened 2020-10-19 10:48 UTC
Hello.

I tried apple login on django-allauth latest version (v0.43.0) and django 3.0.
All settings are like apple settings and added only path('accounts/', include('allauth.urls')), in urls.py

![error](https://user-images.githubusercontent.com/27239125/96441044-6d3cbe80-123b-11eb-8765-1c62f11eaaa7.png)

But when i try with apple login button, i am getting error above
Please give me a solution or sample code

Thanks

**Comment by pennersr** [comment] 2020-10-19 10:56
Your URL looks wrong. I see ".com/%2Fapple/login" -- allauth does not generate urls like that. Proper URL is ".com/accounts/apple/login/". Do you have an altered URL conf ? Closing, not a bug in allauth.

**Closed by pennersr** 2020-10-19 10:56 UTC

**Comment by luckyfanghe** [comment] 2020-10-21 15:54
Please send me a example for apple login?

**Comment by luckyfanghe** [comment] 2020-10-21 15:55
Please send me a example for apple login

**Comment by pennersr** [comment] 2026-06-11 17:03
https://codeberg.org/allauth/django-allauth/issues/2686
