### ISSUE TITLE
Limit Allowed OpenID servers

### ISSUE THREAD

**Issue by spirit2343** [pennersr/django-allauth#1042] opened 2015-07-21 23:07 UTC
in my django settings file in define one SOCIALACCOUNT_PROVIDERS which is to one openid server. Howeve, if a hacker tries to put a different openid server in the login url: /accounts/opneid/login?process=login&openid=<somethingelse> then the application can be used as an attack proxy.

Is there a simple way to address this?

**Comment by pennersr** [comment] 2015-07-21 23:23
Duplicate of #656

**Closed by pennersr** 2015-07-21 23:23 UTC

**Comment by pennersr** [comment] 2026-06-10 19:44
https://codeberg.org/allauth/django-allauth/issues/1042
