### ISSUE TITLE
Need to Fix Application Labels for Django 1.8 

### ISSUE THREAD

**Issue by bkoatz** [pennersr/django-allauth#1127] opened 2015-09-11 14:09 UTC
When people install both soundcloud and allauth.socialaccount.providers.soundcloud, or any provider's python app and their corresponding allauth app if they have the same name, Django throws an ImproperlyConfigured error since Django 1.8 requires unique application names.

Can we update the apps.py and init.py of the allauth provider apps like [here](https://docs.djangoproject.com/en/1.7/ref/applications/#for-application-authors), and make sure the actual name imported is something like soundcloud-allauth instead of just soundcloud so that there aren't name configuration issues in Django 1.8?

Note here for related SO posts:
http://stackoverflow.com/questions/24319558/how-to-resolve-django-core-exceptions-improperlyconfigured-application-labels
http://stackoverflow.com/questions/25397852/django-application-labels-arent-unique-duplicates-bootstrap3

* This isn't an issue for twitter, for example, since their python app name is tweepy. It is though for instagram, soundcloud, etc. I believe we should just update the apps and init.py for all provider apps and make it standard going forward to add -allauth to the app's configuration name

**Comment by asubiotto** [comment] 2015-09-14 18:59
I'm having the same issue

**Comment by pennersr** [comment] 2015-09-17 17:45
Django requires unique app names, but that is referring to the ones in `INSTALLED_APPS`. There is no problem in using a `soundcloud` python module (which is not a Django app) and the SoundCloud provider simultaneously. You may want to look into `from __future__ import absolute_import` ....

Closing, dupe of #393

**Closed by pennersr** 2015-09-17 17:45 UTC

**Comment by pennersr** [comment] 2026-06-10 19:46
https://codeberg.org/allauth/django-allauth/issues/1127
