### ISSUE TITLE
order of fields Login form

### ISSUE THREAD

**Issue by allox** [pennersr/django-allauth#1064] opened 2015-07-29 10:06 UTC
The fields in the login form show up in the wrong  order:
password
remember me 
username

(Django 1.8 , python2.7)

**Comment by pennersr** [comment] 2015-07-29 17:10
Dupe of #1062

**Closed by pennersr** 2015-07-29 17:10 UTC

**Comment by pennersr** [comment] 2026-06-10 19:44
https://codeberg.org/allauth/django-allauth/issues/1064
