### ISSUE TITLE
Support for Sign in with Apple

### ISSUE THREAD

**Issue by oisinbyrne** [pennersr/django-allauth#2362] opened 2019-09-25 13:57 UTC
**Describe the feature**
Are there any plans for 'Sign in with Apple' to be added to the list of providers supported by django-allauth? Apple REST API: https://developer.apple.com/documentation/signinwithapplerestapi

**Additional context**
The Apple REEST API is based on OAuth 2.0 and OpenID Connect, however they use a public/private key client authentication method instead of the typical client secret. New apps uploaded to the iOS App Store with 3rd party social logins are now required to include Sign in with Apple. Existing apps have until April 2020

**Comment by pennersr** [comment] 2019-10-11 13:23
Would definitely like to add support for this, but unless anybody is willing to sponsor development, I am currently unable to allocate resources to this. I will close this issue though as it is not a bug, and keeping this open is not helpful in moving things forward.

**Closed by pennersr** 2019-10-11 13:23 UTC

**Comment by stevejalim** [comment] 2020-03-12 11:41
For other people brought here by search engines and looking for the same thing, there is a PR in progress (by a contributor) at https://github.com/pennersr/django-allauth/pull/2424

**Comment by pennersr** [comment] 2026-06-10 20:57
https://codeberg.org/allauth/django-allauth/issues/2362
