### ISSUE TITLE
Adding a unique_together on emailaddress user_id and primary

### ISSUE THREAD

**Issue by jleclanche** [pennersr/django-allauth#2030] opened 2018-05-22 09:21 UTC
Allauth currently does not set a unique together constraint on user_id and primary. That means a user can end up with multiple primary emails.
Should we add one?

**Comment by pennersr** [comment] 2018-05-22 19:22
Duplicate of: https://github.com/pennersr/django-allauth/issues/225

**Closed by pennersr** 2018-05-22 19:22 UTC

**Comment by pennersr** [comment] 2026-06-10 20:50
https://codeberg.org/allauth/django-allauth/issues/2030
