### ISSUE TITLE
Add email addresses from social accounts when not already associated with the account

### ISSUE THREAD

**Issue by userdefinable** [pennersr/django-allauth#1479] opened 2016-09-05 18:19 UTC
Feature Request

When signing up not via a social account, and then connecting a social account, it would be nice to have the option to add the social account email to account_emailaddress if it's different to those already associated with the account.

**Comment by pennersr** [comment] 2016-09-11 20:40
Dupe of #114

**Closed by pennersr** 2016-09-11 20:40 UTC

**Comment by pennersr** [comment] 2026-06-10 19:55
https://codeberg.org/allauth/django-allauth/issues/1479
