### ISSUE TITLE
Generate fresh access token from refresh token?

### ISSUE THREAD

**Issue by wtfrank** [pennersr/django-allauth#1471] opened 2016-08-27 01:52 UTC
When I've done stuff with OAuth2 before, there is a mechanism to generate a new access_token after the existing one expires.

How do you do this with allauth? I've not spotted anything about this in the docs, nor could I see any obvious functions to do this when I poked around inside socialaccount.

The scenario I've got is that I need to generate a request to a URL that requires an access token, but some time after authentication has taken place the access token has expired, so I need to manually trigger a new token before I makes this call, if we're beyond the expiry time stored with the token.

**Comment by pennersr** [comment] 2016-08-29 10:50
Dupe of #420

**Closed by pennersr** 2016-08-29 10:50 UTC

**Comment by pennersr** [comment] 2026-06-10 19:55
https://codeberg.org/allauth/django-allauth/issues/1471
