### ISSUE TITLE
AttributeError: 'UserSignUpForm' object has no attribute 'try_save'

### ISSUE THREAD

**Issue by ohyeah521** [pennersr/django-allauth#3678] opened 2024-03-10 15:24 UTC
version:0.61.1

```
venv\lib\site-packages\allauth\account\views.py", line 269, in form_valid
    self.user, resp = form.try_save(self.request)
AttributeError: 'UserSignUpForm' object has no attribute 'try_save'
[ERROR] 2024-03-10 23:19:06 - "POST /accounts/signup/ HTTP/1.1" 500 145
[E][django.server][basehttp.py:212] "POST /accounts/signup/ HTTP/1.1" 500 145
```

**Comment by pennersr** [comment] 2024-03-10 19:48
alauth has no `UserSignUpForm` -- you're likely not extending/changing the signup form properly. In any case, closing -- not a bug in allauth.

**Closed by pennersr** 2024-03-10 19:48 UTC

**Comment by pennersr** [comment] 2026-06-12 10:27
https://codeberg.org/allauth/django-allauth/issues/3678
