### ISSUE TITLE
mixing sessions

### ISSUE THREAD

**Issue by CMNDER** [pennersr/django-allauth#2692] opened 2020-10-22 14:43 UTC
with django-allauth when an admin user logs in then he is logged in even in the formal application preventing normal users to log in on the same computer there is no separation of sessions at all

**Comment by pennersr** [comment] 2020-10-22 19:28
This is the way things work for Django sessions -- it is not a bug in allauth.  Closing.

**Closed by pennersr** 2020-10-22 19:28 UTC

**Comment by pennersr** [comment] 2026-06-11 17:03
https://codeberg.org/allauth/django-allauth/issues/2692
