### ISSUE TITLE
Reset password link is not working for 0.35.0

### ISSUE THREAD

**Issue by huaying** [pennersr/django-allauth#1948] opened 2018-02-15 04:34 UTC
Hi,

I just upgraded from 0.33 to 0.35.

In the new version, the reset password link always displays a "Bad Token." It seems that [this line](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L590) is always false, which could be the cause of the problem.

Anyone have any idea what happened? Thanks.

**Comment by changchichung** [comment] 2018-03-14 09:09
I have the same problem, any solutions ?

**Comment by pennersr** [comment] 2018-03-14 09:16
The password reset flow is extensively tested in the unit tests. I would also expect way more complaints if something was really wrong in allauth on this point.  You can try to set a breakpoint  in PasswordResetFromKeyView.dispatch just before the form.is_valid(). Please double check if the token is stored in the session correctly.

**Comment by l3szcz** [comment] 2018-04-15 17:35
I'm also having this issue on my production env which is behind Varnish Cache. The problem is not present on my dev env without Varnish. I'm waiting for a server admin to exclude the page from cache, will report back if it fixes the issue.

**Comment by epicserve** [comment] 2018-04-27 14:36
@pennersr Any idea why these lines are commented out?
https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L520

I override this method and was trying to update it after upgrading to 0.35.0 and the password reset workflow doesn't seem to be working because it's not saving the key to the database.

**Comment by epicserve** [comment] 2018-04-27 14:37
Looking at the blame, they've been commented out for 8 years. Hmmm ... so where is the key saved to the database?

**Comment by tysonclugg** [comment] 2018-05-08 04:41
I'm guessing this issue is related to #2015 where the password reset key is stored in the browser session, rather than encoded in the password reset URL.

**Comment by epicserve** [comment] 2018-05-08 14:07
@tysonclugg I was actually able to determine that our issue was caused when we updated to a newer version, because of how we subclassed some of the allauth forms.

**Comment by huaying** [comment] 2018-05-19 03:54
Hi everyone, I found that we had a problem because the default token generator was [changed](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L51) from `django.contrib.auth.tokens.default_token_generator` to `EmailAwarePasswordResetTokenGenerator()`, while we implemented our own reset password form with the old default token generator. We would switch to the `EmailAwarePasswordResetTokenGenerator()`, except we support user accounts that don't have email addresses (using phone number instead). Are there any alternatives?

**Comment by pennersr** [comment] 2018-05-21 15:31
Closing -- this is unlikely to be an issue in allauth.

**Closed by pennersr** 2018-05-21 15:31 UTC
Labels: Unconfirmed

**Comment by dev-vladyslav-kulyk** [comment] 2022-07-22 16:13
> Hi everyone, I found that we had a problem because the default token generator was [changed](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L51) from `django.contrib.auth.tokens.default_token_generator` to `EmailAwarePasswordResetTokenGenerator()`, while we implemented our own reset password form with the old default token generator. We would switch to the `EmailAwarePasswordResetTokenGenerator()`, except we support user accounts that don't have email addresses (using phone number instead). Are there any alternatives?

The best solution ever! It works. 
Thanks xoxoxo

**Comment by pennersr** [comment] 2026-06-10 20:47
https://codeberg.org/allauth/django-allauth/issues/1948
