### ISSUE TITLE
Network Login Failure error reporting is QUITE unhelpful

### ISSUE THREAD

**Issue by derek-adair** [pennersr/django-allauth#2142] opened 2018-11-01 17:38 UTC
Currently if my social account integration is not set up properly, I'm left having to dig into the code to debug.  It'd be a fantastic improvement for debugging if we could make this generic fail more helpful. 

- {{ auth_error }} returned in debug mode
- Exact errors reported via the error console/logs (even w/o debug=True)

I'm sure there are other improvements that can be made in this regard.

I'd be glad to dive in and get this done if no one else had the bandwidth.

**Comment by derek-adair** [comment] 2018-11-01 18:29
Specifically using twitter.  Which seems to NOT be related to #1120? unsure tho.

**Comment by kov** [comment] 2021-05-12 13:05
This is very frustrating and it is a bit surprising that it has been an issue for so long (the first issue I hit on my search was from 2014). I am working on a dockerized application so it's not very easy to debug things or make changes. Why not simply provide at least some detail in the logs at least so that you don't risk exposing something you shouldn't to users. It really shouldn't be that hard to do, right?

**Comment by pennersr** [comment] 2023-07-06 06:22
Dupe of #1120

**Closed by pennersr** 2023-07-06 06:22 UTC

**Comment by derek-adair** [comment] 2023-07-06 14:52
my bad dude.  Thanks for your work.

Would you be open to someone help you triage issues?

**Comment by pennersr** [comment] 2023-07-06 15:32
Sure, there is nothing preventing anyone from hopping onto an issue and doing the research.

**Comment by derek-adair** [comment] 2023-07-06 16:39
Sure, I'll try to comment where I can.  I meant in a more official capacity -- e.g. closing issues for you or escalating valid ones -- which would require us being on the same page with your ambitions and approach to open source.

**Comment by pennersr** [comment] 2026-06-10 20:52
https://codeberg.org/allauth/django-allauth/issues/2142
