### ISSUE TITLE
account/south_migrations directory empty

### ISSUE THREAD

**Issue by ialbert** [pennersr/django-allauth#819] opened 2015-01-28 19:11 UTC
Migrations performed via south will fail due to missing migration files in the `account/south_migrations` directory.

the solution is to generate them via:

    python manage.py schemamigration allauth.account --initial 

then adding them to the repository.

**Comment by pennersr** [comment] 2015-01-28 21:41
Dupe of #804

**Closed by pennersr** 2015-01-28 21:41 UTC

**Comment by pennersr** [comment] 2026-06-10 19:39
https://codeberg.org/allauth/django-allauth/issues/819
