### ISSUE TITLE
Can't override "password_reset_key_message.txt"

### ISSUE THREAD

**Issue by MadReal** [pennersr/django-allauth#1885] opened 2017-11-17 16:43 UTC
Hello, I'm having issues override the default email for the "forgot password". I can override the 2 email for "email confirmation" without any issue but not with this one.

Not matter the extension, the one sent is always the default one that comes with the package.

Thanks

**Comment by pennersr** [comment] 2017-12-11 18:37
I am sorry, I am quite sure this is not a bug in allauth, but rather an issue in your deployment. So I will have to close this issue.

**Closed by pennersr** 2017-12-11 18:37 UTC

**Comment by Koomook** [comment] 2018-12-20 04:54
I got same issue. any improvement here?

**Comment by pennersr** [comment] 2026-06-10 20:46
https://codeberg.org/allauth/django-allauth/issues/1885
