### ISSUE TITLE
Password reset fails if `messages` framework is enabled 

### ISSUE THREAD

**Issue by jagguli** [pennersr/django-allauth#3189] opened 2022-11-15 12:01 UTC
```
File "/usr/local/lib/python3.10/sit
e-packages/allauth/account/views.py", line 105, in post
    response = self.form_valid(form)
  File "/u
sr/local/lib/python3.10/site-packages/allauth/account/views.py", line 805, in form_valid
    adapter.add_
message(
  File "/usr/local/lib/python3.10/site-packages/allauth/account/adapter.py", line 337, in add_m
essage
    messages.add_message(request, level, message, extra_tags=extra_tags)
  File "/usr/local/lib/p
ython3.10/site-packages/django/contrib/messages/api.py", line 40, in add_message
    return messages.add(
level, message, extra_tags)
  File "/usr/local/lib/python3.10/site-packages/drf_messages/storage.py", li
ne 121, in add
    Message.objects.create_message(self.request, message, level, extra_tags=extra_tags)

File "/usr/local/lib/python3.10/site-packages/drf_messages/models.py", line 100, in create_message
    m
essage_obj = self.create(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py",
line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/l
ocal/lib/python3.10/site-packages/django/db/models/query.py", line 669, in create
    obj = self.model(**
kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 541, in __init__

    _setattr(self, field.name, rel_obj)
  File "/usr/local/lib/python3.10/site-packages/django/db/model
s/fields/related_descriptors.py", line 235, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fbf0e2caef0>>
>": "Message.user" must be a "User" instance.", "lineno": 99, "filename": "request.py", "func_name": "
process_exception"}
```

**Comment by iarp** [comment] 2022-11-30 20:40
The issue isn't with allauth. It's with drf-messages is attempting to store a message and assign it to a user that doesn't exist (anonymous). You need to discuss this with drf-messages people.

You can test this by running django, making sure you're not logged in and in the view add a `messages.success(request, 'test')` and it'll error as well.

**Closed** 2022-11-30 20:45 UTC

**Comment by pennersr** [comment] 2026-06-11 17:16
https://codeberg.org/allauth/django-allauth/issues/3189
