### ISSUE TITLE
Duplicate Users with Different Case Being Created After Upgrade

### ISSUE THREAD

**Issue by jplehmann** [pennersr/django-allauth#1907] opened 2017-12-12 16:06 UTC
I just upgraded from 0.20 to 0.32 yesterday (I'm still on Django 1.8).  Everything seemed to go fine, and then I saw an error caused by a user with a duplicate name.  In the last day, a number of users have registered with names that shouldn't be allowed.  They seem to be registering with Facebook login.  In each case, the new user is the lowercase name, whereas the old user is the init cap name (adam vs Adam).

The aggravating thing is that I have been unable to reproduce the problem. It seems to be working correctly to me. I correctly can't seem to register a username if any case of that name is taken.

I have default values of `ACCOUNT_PRESERVE_USERNAME_CASING` which should be True (Yes I would like to make this False soon).  This may be what I have to do if I cannot solve this bug.

Also, I override `DefaultAccountAdapter.clean_username` which calls super. I could see this behavior happening if shallow was True.  I simply pass the value through, however.

Different but relates to #1868.

**Comment by jplehmann** [comment] 2017-12-13 15:47
Since I could not reproduce the issue (even though my users constantly were!), I am attempting to move past it by dropping casing of usernames.

In other words, I just went live with:
```
ACCOUNT_PRESERVE_USERNAME_CASING = False
```
And:
```
UPDATE auth_user SET username = LOWER(username);
```
And then I cleaned up the duplicate accounts and notified those users.

**Comment by JereMalinen** [comment] 2018-06-21 14:48
We are also experiencing the same problem with 0.30 and Django 1.11. 0.26.1 with Django 1.9 is working fine. Also not able reproduce on dev environments, but happened multiple times in production until rollback. Users didn't type username so it was probably generated by allauth wrongly, can't just figure out how...

```
IntegrityError: (1062, "Duplicate entry 'jere' for key 'username'")

...
  File "allauth/socialaccount/views.py", line 53, in form_valid
    form.save(self.request)
  File "allauth/socialaccount/forms.py", line 27, in save
    user = adapter.save_user(request, self.sociallogin, form=self)
  File "allauth/socialaccount/adapter.py", line 77, in save_user
    get_account_adapter().save_user(request, u, form)
  File "allauth/account/adapter.py", line 239, in save_user
    user.save()
  File "django/contrib/auth/base_user.py", line 80, in save
    super(AbstractBaseUser, self).save(*args, **kwargs)
  File "django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
  File "MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
```

**Comment by ClearSky0** [comment] 2023-06-14 10:21
Does ACCOUNT_PRESERVE_USERNAME_CASING actually do anything at the moment?

https://github.com/search?q=repo%3Apennersr%2Fdjango-allauth%20ACCOUNT_PRESERVE_USERNAME_CASING&type=code

**Comment by ClearSky0** [comment] 2023-06-14 11:38
I misunderstood what was happening with my project due to having used Django admin to update usernames.

With ACCOUNT_PRESERVE_USERNAME_CASING = False usernames are stored in lowercase on the user model table.

If you then update the username and add case to it using the Django admin, as I had done.   Then the username isn't checked when looking for duplicates, and it is therefore possible to create a username with the same chars but different case.  Hope this offers clues to anyone having the similar issues.

**Comment by pennersr** [comment] 2023-06-19 21:02
Closing -- outdated.

**Closed by pennersr** 2023-06-19 21:02 UTC

**Comment by pennersr** [comment] 2026-06-10 20:46
https://codeberg.org/allauth/django-allauth/issues/1907
