### ISSUE TITLE
Going from ACCOUNT_EMAIL_VERIFICATION "optional" to "mandatory"

### ISSUE THREAD

**Issue by skrivanos** [pennersr/django-allauth#1744] opened 2017-05-28 11:23 UTC
Is there a way to do this so that the mandatory verification only applies to new users? Of course I could in theory update the database and set verified to True on all emails but that would be corrupting the data.

**Comment by pennersr** [comment] 2017-07-27 06:12
What is needed here is to add some kind of get_email_verification_mode(user) to the adapter class, instead of looking it up at a fixed setting. Then, you would be able to put any kind of logic in there, like if user.date_joined >= 2017-07-25 and so on...

**Comment by pennersr** [comment] 2017-07-27 06:17
Marking as duplicate of #1776

**Closed by pennersr** 2017-07-27 06:17 UTC
Labels: Feature request

**Comment by pennersr** [comment] 2026-06-10 20:41
https://codeberg.org/allauth/django-allauth/issues/1744
