### ISSUE TITLE
Different handling of email addresses social login vs connecting a social account?

### ISSUE THREAD

**Issue by pjmcdermott** [pennersr/django-allauth#1882] opened 2017-11-17 10:13 UTC
I am playing around with `allauth` and I am seeing different (inconsistent?) behaviour with regard to email addresses, which is puzzling me from a user experience point of view:

- If I create a **new** account via social login, the email address associated with the social network account is included in the list of email addresses under `/accounts/email`.
- If I have an **existing** account and add a new social network connection, the email address associated with the social network is **not** included in the list of email addresses under `/accounts/email`. (I appreciate that the user may manually add any associated email address if they wish).
- Moreover, it is then (correctly) not possible to add a new account using the same social network email address either via a new account creation or via social login, as the email address is (rightly) flagged as being associated with another account--**but this is not visible to the user in the user interface**.

This confused me at first. The treatment of social network email addresses appears inconsistent to me from a user experience perspective.

Is there a rationale from the current behaviour that I am missing?

**Comment by pennersr** [comment] 2017-11-18 12:47
Dupe of https://github.com/pennersr/django-allauth/issues/114#issuecomment-8576150

**Closed by pennersr** 2017-11-18 12:47 UTC

**Comment by pennersr** [comment] 2026-06-10 20:46
https://codeberg.org/allauth/django-allauth/issues/1882
