### ISSUE TITLE
KeyError at /auth/login/

### ISSUE THREAD

**Issue by tochimclaren** [pennersr/django-allauth#3361] opened 2023-07-24 08:19 UTC
I get KeyError when I install any social auth application in the INSTALLED_APP list in settings.py
Python version: 3.11.2
Pipenv: 2022.5.2
Allauth version: 0.54.0
OS: ubuntu: 20.04 LTS

`Traceback (most recent call last):
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/allauth/socialaccount/templatetags/socialaccount.py", line 19, in render
    provider = providers.registry.by_id(provider_id, request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomms/.local/share/virtualenvs/ecommerce-u0AC6Sae/lib/python3.11/site-packages/allauth/socialaccount/providers/__init__.py", line 21, in by_id
    return self.provider_map[id](request=request)
           ~~~~~~~~~~~~~~~~~^^^^
KeyError: <allauth.socialaccount.providers.google.provider.GoogleProvider object at 0x7fe7078100d0>
`

**Comment by pennersr** [comment] 2023-07-24 19:35
Are you sure you have all dependencies installed, such as `requests` and `requests-oauthlib`? In any case, this is not a bug in allauth, this points to a local environment issue. Closing.

**Closed by pennersr** 2023-07-24 19:35 UTC

**Comment by pennersr** [comment] 2026-06-11 17:21
https://codeberg.org/allauth/django-allauth/issues/3361
