### ISSUE TITLE
session expired after browser close when logged in with account_login

### ISSUE THREAD

**Issue by wizbaselc** [pennersr/django-allauth#2111] opened 2018-09-14 04:48 UTC
Hi,

There is no problem with social login which means the session remains even the browser re-opened.
But when I do login with email and password directly to my site by using account_login url, the session is expired after re-open browser.

Is there a way to keep session for direct logged in user after browser re-open?

**Comment by derek-adair** [comment] 2023-08-27 13:25
1. The "remember me" checkbox works for me with direct account login.
2. This issue makes me suspect that social accounts are always stored in a django session, which is concerning.  I don't have a social login app ready to test this... but if the "remember me" works as intended this can be closed.

**Comment by pennersr** [comment] 2023-08-27 20:07
Closing as dated.

**Closed by pennersr** 2023-08-27 20:07 UTC

**Comment by pennersr** [comment] 2026-06-10 20:52
https://codeberg.org/allauth/django-allauth/issues/2111
