### ISSUE TITLE
Headless API creating user in dev db instead of test db

### ISSUE THREAD

**Issue by Jsalaz1989** [pennersr/django-allauth#3917] opened 2024-06-24 15:46 UTC
Thanks @pennersr for developing the headless API. Specifically I was brought here due to [your comment in a django-ninja thread regarding Google social auth](https://github.com/vitalik/django-ninja/issues/479#issuecomment-2051394447).

I don't know if I'm missing something but during testing (I'm using `pytest`) the [login](transactional_db: None) or signup endpoints are pointing at the dev db instead of the test db. I've tried with `@pytest.mark.django_db(transaction=True)` as well as the `transactional_db` fixture but the new user is always being created in the dev db instead of the test db.

**Comment by pennersr** [comment] 2024-06-24 19:23
Not sure what is going on in your test suite, but this is in any case not a bug in allauth, so I have to close this.

**Closed by pennersr** 2024-06-24 19:23 UTC

**Comment by Jsalaz1989** [comment] 2024-06-24 20:47
Sorry, I got excited and immediately started throwing `requests.post()` at the API instead of `client.post()` from `django.test.Client`. It's working now...

**Comment by pennersr** [comment] 2026-06-12 10:33
https://codeberg.org/allauth/django-allauth/issues/3917
