### ISSUE TITLE
Question about account/migrations/0005_...

### ISSUE THREAD

**Issue by afuetterer** [pennersr/django-allauth#3417] opened 2023-09-07 04:59 UTC
Hi there,

this is my first issue here, so please close, if there is another/better place to post such a question.

I have updated a project to use django-allauth 0.55.2 this week. In my /.venv/lib/python3.11/site-packages there is no "allauth/account/migrations/0005_emailaddress_idx_upper_email.py" migration file, like the one I see on GitHub.

If I run `makemigrations` though, Django generates another migration file starting with 0005:

```console
$ python manage.py makemigrations
Migrations for 'account':
  /.../.venv/lib/python3.11/site-packages/allauth/account/migrations/0005_alter_emailaddress_email.py
    - Alter field email on emailaddress
```

The contents differ from the one on GitHub:
```python
# Generated by Django 3.2.21 on 2023-09-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_emailaddress_drop_unique_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=190, verbose_name='email address'),
        ),
    ]
```

Is this going to be a problem with the next update? Or am I doing something wrong here?

Thanks.

Context:
```console
$ pip show django        
Name: Django
Version: 3.2.21
...

$ pip show django-allauth        
Name: django-allauth
Version: 0.55.2
...

**Comment by pennersr** [comment] 2023-09-07 08:14
Thanks for reporting. This is an issue. The issue is that the email max length is configurable through a setting, though, its value cannot be altered on the fly as that impacts migrations. The migrations refer to this setting as well, and here something went wrong: migration 0004 has the value hardcoded instead of referring to the setting, and your project apparently uses 190 instead of the default 254.

**Comment by pennersr** [comment] 2023-09-07 08:19
Fixed via: 1c67e503

**Comment by afuetterer** [comment] 2023-09-07 08:20
I see. Thanks for the quick reply and fix.

Should we change something in our settings then?

**Closed by pennersr** 2023-09-07 08:19 UTC
Labels: FIXME

**Comment by pennersr** [comment] 2023-09-07 09:27
I recommend you upgrade to 0.56.0

**Comment by afuetterer** [comment] 2023-09-07 11:36
Alright, thanks a lot.

**Comment by pennersr** [comment] 2026-06-11 17:22
https://codeberg.org/allauth/django-allauth/issues/3417
