### ISSUE TITLE
Reddit: Social Network Login Failure

### ISSUE THREAD

**Issue by gustavklopp** [pennersr/django-allauth#1244] opened 2016-01-02 06:19 UTC
I've successfully implemented django-allauth for Stackexchange but can't get it working with Reddit.

I've got the screen where I authorized the app, then after it, I'm sent to : http://localhost:8000/accounts/reddit/login/callback/?state=(some numbers...)&code=(some numbers...):
```
Social Network Login Failure
An error occurred while attempting to login via your social network account.
```
**in https://www.reddit.com/prefs/apps :**
MyApp
web ap
(some app id)

secret: (some secret key)
name: MyApp
description: MyApp
about url: 
redirect uri: http://localhost:8000/accounts/reddit/login/callback/

**in http://localhost:8000/admin/socialaccount/socialapp/**
Provider: Reddit
name: MyApp
client id: (some App id)
secret key: (some secret key)
chosen site: example.com

**in settings.py** 
I've only put, in addition to the requirements written in the docs:
`LOGIN_REDIRECT_URL = 'main_page'`

**Comment by gustavklopp** [comment] 2016-01-02 06:35
So confused..
Now I've come to http://localhost:8000/accounts/social/connections/ , choose the "Reddit" provider, and it worked!

And now, when I logged out, and try to login using my link in one of my template:
`<a role="button" class="btn btn-success" href="{% provider_login_url 'reddit' %}">Authenticate via Reddit.com</a>`

it's working. Is it a problem with the link to the provider? (solved by going to http://localhost:8000/accounts/social/connections/  by some ways...)

**Comment by pennersr** [comment] 2016-03-11 18:17
Debugging project specific setups is not feasible for me. I would say use pdb to step through the OAuth2CallbackView.dispatch() code (allauth.socialaccount.providers.oauth2.views).. then inspect the OAuth2Error or PermissionDenied that is likely the cause of your failure. Closing... if you bump into an issue in allauth that needs fixing feel free to reopen.

**Closed by pennersr** 2016-03-11 18:17 UTC

**Comment by pennersr** [comment] 2026-06-10 19:49
https://codeberg.org/allauth/django-allauth/issues/1244
