### ISSUE TITLE
Detect duplicate emails in social logins

### ISSUE THREAD

**Issue by wmorrell** [pennersr/django-allauth#1274] opened 2016-02-02 01:37 UTC
This is admittedly an edge case.

Consider a user has an existing account in a Django site using a Google email. The site enables logging in via Google account with allauth. This will trigger the socialaccount/signup.html page, because the email address on the Google account matches an existing email on an account. However, the user must first submit the signup form, before seeing the error message that an existing account is using that email.

I would propose a behavior change in the previous scenario, where the user gets redirected to the login page with the error about an existing account with `{{ email }}`.

**Comment by pennersr** [comment] 2016-02-03 23:22
Dupe of #215 (see 2nd bullet of comment https://github.com/pennersr/django-allauth/issues/215#issuecomment-15019267)

**Closed by pennersr** 2016-02-03 23:22 UTC

**Comment by wmorrell** [comment] 2016-02-04 00:23
Whoops, did not check nearly far back enough. I'll watch that one instead, thanks for the heads up!

**Comment by pennersr** [comment] 2026-06-10 19:49
https://codeberg.org/allauth/django-allauth/issues/1274
