### ISSUE TITLE
Generating 6 digit verification code during registration

### ISSUE THREAD

**Issue by waqqasjabbar** [pennersr/django-allauth#3014] opened 2022-01-25 13:57 UTC
Hi,

I want to send a 6 digit code to the user in email on registration. I disabled the HMAC based code generation (ACCOUNT_EMAIL_CONFIRMATION_HMAC = False). The code that is generated is a 64 digit alpha-numeric string.

Based on my reading of the code, it is generated from [this line](https://github.com/pennersr/django-allauth/blob/ced1ddc730c36eca3551406c60e1577e30e01cbd/allauth/account/models.py#L101)

Is there a way to over-ride this to fulfil my requirement. It would be great if we can specify `EmailConfirmation` class through configuration and have a function like `get_email_confirmation_model()` that returns the currently configured model, similar to what `AUTH_USER_MODEL` do in [django authentication](https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#substituting-a-custom-user-model)

Thanks

**Comment by some1ataplace** [comment] 2022-02-09 19:09
Duplicate of #2061

**Comment by pennersr** [comment] 2022-02-09 20:44
If you disabled HMAC, you can override the `generate_emailconfirmation_key` method of the account adapter and make it return a 6 digit number.

**Comment by bene25** [comment] 2022-04-10 19:21
@waqqasjabbar I made it with 2 changes in account.adapter 
```
    def generate_emailconfirmation_key(self, email):
        # key = get_random_string(64).lower()
        key = random.randrange(100000, 999999)
        return key
```

and 

```
    def send_confirmation_mail(self, request, emailconfirmation, signup):
        current_site = get_current_site(request)
        # activate_url = self.get_email_confirmation_url(request, emailconfirmation)
        activate_url = emailconfirmation.key
        ctx = {
            "user": emailconfirmation.email_address.user,
            "activate_url": activate_url,
            "current_site": current_site,
            "key": emailconfirmation.key,
        }
        if signup:
            email_template = "account/email/email_confirmation_signup"
        else:
            email_template = "account/email/email_confirmation"
        self.send_mail(email_template, emailconfirmation.email_address.email, ctx)
```

also changed email text in templates

**Comment by okapies** [comment] 2022-09-06 13:11
It seems the above solution is not sustainable because `key` is a unique field. `EmailConfirmation` model can contain up to 900,000 rows.

```python
key = models.CharField(verbose_name=_("key"), max_length=64, unique=True)
```

**Comment by bene25** [comment] 2022-12-13 08:33
@okapies you are correct.
- we can increase number of digits, for example from 6 to 8 then we will have up to 90, 000,000 rows. But for long term solution it doesn't fit very well.
- or we can remove `Unique` from `key` field and it's constraint, but in this case we will have cases when user can verify email for other user if codes will match.
-  preferred solution is to have `key` field (without uniqueness) or add another field, especially for six digits code, and check associated email with code during verification.

**Comment by ml-jobalerts** [comment] 2023-11-29 09:59
Hi,
What was the conclusion of this discussion? Is there an alternative to links available now?
Microsoft safelink protection breaks signup confirmation by links.
https://security.stackexchange.com/questions/230309/is-a-safelinks-protection-outlook-com-link-phishing

**Comment by pennersr** [comment] 2023-11-29 17:51
Reopening because this...

https://github.com/pennersr/django-allauth/issues/3014#issuecomment-1034175249

... is indeed incorrect because of:

https://github.com/pennersr/django-allauth/issues/3014#issuecomment-1238131234

**Comment by pennersr** [comment] 2023-12-01 15:08
Closing again -- missed that it was also a duplicate of #2061

**Closed by pennersr** 2023-12-01 15:08 UTC

**Comment by pennersr** [comment] 2026-06-11 17:12
https://codeberg.org/allauth/django-allauth/issues/3014
