### ISSUE TITLE
Is there a way to generate an auto-login link?

### ISSUE THREAD

**Issue by Danilka** [pennersr/django-allauth#2438] opened 2020-01-13 00:52 UTC
Many apps email people with a direct link that logs users in automatically. Is there a way to do this with all-auth? If not maybe to consider this as a feature request?

**Comment by anthonynsimon** [comment] 2020-01-18 23:29
@Danilka I've been using this lib with great success: https://github.com/aaugustin/django-sesame

It was quite easy to integrate with the rest of the project.

It comes down to something like this (some of it depends on your project):
```
# Use this function to generate the magic link when the user requests it and then just send it via email
from sesame.utils import get_query_string

def get_magic_link(request, user):
    magic_link = get_query_string(user)
    return request.build_absolute_uri(f"{reverse('magic-link-auth')}{magic_link}")

...

# This would be the view in which you validate the link and login the user
from sesame.utils import get_user
from django.contrib.auth import authenticate, login

def authenticate_magic_link(request):
    user = get_user(request)
    if user is None:
        return HttpResponseBadRequest()
    login(request, user)
    to = getattr(settings, "ACCOUNT_LOGIN_REDIRECT_URL", "/")
    return redirect(to)
```

**Comment by Danilka** [comment] 2020-01-22 23:37
@anthonynsimon thank you so much for sharing this! Looks like a great lib, I'll give it a go.
For now I'm using [](https://github.com/lamby/django-autologin) but it has it's limitations, while being extremely simple.
It seems like such an option should be built into the all-auth though.

**Comment by bittner** [comment] 2020-03-06 20:06
This is likely a duplicate of #1472.

**Comment by pennersr** [comment] 2021-12-17 10:22
Dupe of #1472 indeed

**Closed by pennersr** 2021-12-17 10:22 UTC

**Comment by pennersr** [comment] 2026-06-10 20:59
https://codeberg.org/allauth/django-allauth/issues/2438
