### ISSUE TITLE
Not following ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION or ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL settings

### ISSUE THREAD

**Issue by apardes** [pennersr/django-allauth#633] opened 2014-06-11 00:42 UTC
I am trying to log the user in after they confirm their email and then redirect them to a given page however neither of these settings are affecting the flow properly. 

After confirming their email the user is redirected to my index (not the specified view) and is still required to log in manually.

```
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL ='app:createStudent'
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'app:createStudent'
LOGIN_REDIRECT_URL = 'app:index'
ACCOUNT_LOGOUT_REDIRECT_URL = 'app:index'
```

See the question here: http://stackoverflow.com/questions/24152139/django-allauth-does-not-log-user-in-on-email-confirm

**Comment by jplehmann** [comment] 2015-06-11 14:01
I am having a similar issue, using version `0.20.0`.  When a user creates an account and immediately verifies their email, allauth is not redirecting to `ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL` as expected, but rather to `/`.  I debugged the issue, and in `ConfirmEmailView.post()`, the following code executes before getting to the part about redirection:
```
        if app_settings.LOGIN_ON_EMAIL_CONFIRMATION:
            resp = self.login_on_confirm(confirmation)
            if resp is not None:
                return resp
```
The `get_redirect_url()` which makes use of the said parameter occurs right after. I tried obtaining `redirect_url` earlier and using it in this block, but ran out of time and am not sure of other behaviors I might break.

My workaround was to set `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` to false, so that that code never executes. While the user is now forced to always re-login, at least they will be sent to my custom redirect page (which continues their account creation process).

A patch for this issue would be great!

**Comment by gacpro** [comment] 2015-07-13 00:18
I'm experiencing a similar issue with social accounts. I'm using Django 1.8.1 and AllAuth 0.19.1, when a user sings up with Facebook and then confirms his/her email address, a login is attempted and the following message shows up: "Account Inactive. This account is inactive."

I tried a signal callback to email_confirmed to set the user to active but it didn't work regardless the user is actually set to active. It seems AllAuth keeps an old reference to the user so it doesn't aware that the signal has changed the user to active.

A fix to this issue will be really appreciated.

**Comment by chubz** [comment] 2015-09-10 11:08
I've had a similar issue where the request was to change some login related info in a signal email_confirmed.
I guess the view has user taken from confirmation object and didn't have fresh values which leads to login not working down the road.
I guess it would be good that login_on_confirm should always have a fresh user instance in case any of the signals made changes that are relevant to the login process.
https://docs.djangoproject.com/en/dev/ref/models/instances/#refreshing-objects-from-database
this seems relevant to this issue (but is limited to 1.8) and I can check newer version and if I can reproduce my problem with it. 
@gacpro you can just do confirmation view override and ensure that user instance is fresh. put the confirmation url in urls before accounts and override the view in app before allauth in apps. Something like: User.objects.get(email=confirmation.email_address.email) in login_on_confirm method

**Comment by chubz** [comment] 2015-09-22 11:52
@pennersr any thoughts on this "issue"? 
I'm talking about [this line](https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L278) having a stale user if anything regarding login is done via email_confirmed signal.

**Comment by sowinski** [comment] 2016-02-11 11:12
I have the same issue. Is there a workaround for this? 
>> The ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True settings works only when the user >> performs a sign-up action and verifies the email in the same browser session. 
>> Source (http://stackoverflow.com/questions/24152139/django-allauth-does-not-log-user-in-on-email-confirm)
Is it possible to disable this behavior? I have users who opens the activation email a view hours later and then they are not logged in after email confirmation.

**Comment by derek-adair** [comment] 2023-08-27 12:06
@pennersr The user should be logged in on email confirmation no matter what (IMO) assuming it can be done securely.  At a minimum it may be worth looking into if this can be done w/ the setting across browser sessions somehow but that seems unlikely w/o exposing passwords.

**Comment by derek-adair** [comment] 2023-08-27 12:11
@pennersr I feel pretty strongly that allauth should redirect to the LOGIN_URL by default, if set.... BUT... if that's not something you agree with *shrug...

**Regarding this issue specifically:** If it is a security limitation to not do this across sessions (it probably is) -- this can be closed.

**Comment by pennersr** [comment] 2023-08-27 20:15
Closing as dated

**Closed by pennersr** 2023-08-27 20:15 UTC

**Comment by ThukuWakogi** [comment] 2024-05-28 21:03
I'm using version 0.63.2 and this is still a problem

I worked around this by inheriting `DefaultAccountAdapter` and overiding `get_email_verification_redirect_url` and returning the url i wanted, then setting the adapter in `settings.py`

This is what my code looks like


```py
# /path/to/adapters.py
from allauth.account.adapter import DefaultAccountAdapter


class AccountAdapter(DefaultAccountAdapter):
    def get_email_verification_redirect_url(self, email_address):
        return "http://my.domain.com/email-confirmation-successful"
```

```py
# settings.py

ACCOUNT_ADAPTER = "path.to.adapters.AccountAdapter"
```

**Comment by pennersr** [comment] 2026-06-10 17:25
https://codeberg.org/allauth/django-allauth/issues/633
