### ISSUE TITLE
Issues with LinkedIn Authentication?

### ISSUE THREAD

**Issue by matinde** [pennersr/django-allauth#3589] opened 2024-01-08 09:40 UTC
I just wanted to know if the current version of django-allauth works with the new authentication for Linkedin? When I create a Linkedin app, the scope on the app are as follows. 

![Authentication _ App detail _ Developers _ LinkedIn](https://github.com/pennersr/django-allauth/assets/18006636/9b2e135a-57f2-45cf-931f-a89e51f42568)

This is inconsistent to the auth error received in the django app: 
"GET /accounts/linkedin_oauth2/login/callback/?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application&state=tQDDdzzhvwKAD3eA HTTP/1.1" 200 946

Currently thinking of not using Linkedin cause it has become too complicated to make the application work.

**Comment by pennersr** [comment] 2024-01-08 18:39
Duplicate of: https://github.com/pennersr/django-allauth/issues/3558#issuecomment-1849033044 -- just use the OIDC provider.

**Closed by pennersr** 2024-01-08 18:39 UTC

**Comment by pennersr** [comment] 2026-06-12 10:26
https://codeberg.org/allauth/django-allauth/issues/3589
