### ISSUE TITLE
default_auto_field for all models

### ISSUE THREAD

**Issue by mohammad2goodarzi** [pennersr/django-allauth#2939] opened 2021-08-31 07:20 UTC
All models have IDs. But django-allauth models do not.
So when we use django-allauth in our project, it creates a migration file which leads to some problems.

**Comment by 9mido** [comment] 2021-08-31 12:08
Isn't this a duplicate of #2829 and #2826?

**Comment by mohammad2goodarzi** [comment] 2021-08-31 12:44
No. I tried their method. It does not solve the problem.
The problem is that migrations files must already exist in django-allauth.

**Comment by pennersr** [comment] 2021-12-14 20:45
Closing, it's there now.

**Closed by pennersr** 2021-12-14 20:45 UTC

**Comment by pennersr** [comment] 2026-06-11 17:10
https://codeberg.org/allauth/django-allauth/issues/2939
