### ISSUE TITLE
Bypass social signup for existing account

### ISSUE THREAD

**Issue by martinsvoboda** [pennersr/django-allauth#1149] opened 2015-10-10 23:36 UTC
Goal: Bypass showing social singup form if user already created account via other login method.

Scenario (actual):

1.  User created account via registration form with email (test@test.com) and password.
2.  User logout from system.
3.  User try to login via Facebook (his Facebook email is also test@test.com).
4. System show /accounts/social/singup/ form, asking to set username and email (prefilled test@test.com).
5. User submit form and got error "Email is already in use ...". That is wrong.

I think we can improve this process. Before showing /accounts/social/singup/ form, try to check if already exists account with same as FB email (test@test.com).
* If **account exist**, redirect user to login page and inform him "You already create your account using the email and password. Please log in this way. After you log in, you will be able to use and login using Facebook.". After login via email and password automatically connect with his Facebook account.
* If **account not exists** singup process can continue in normal way

I implemented on my custom site without forking django-allauth (only extends SocialSignupVIew and  connect to user_logged_in signal). I am using only Facebook and email/password auth methods. My changes:

```python
# Extends SocialSignupView to redirect to login page if already exists account with same email
class CustomSocialSignupView(SignupView):
    def dispatch(self, request, *args, **kwargs):
        self.sociallogin = None
        data = request.session.get('socialaccount_sociallogin')
        if data:
            self.sociallogin = SocialLogin.deserialize(data)
        if not self.sociallogin:
            return HttpResponseRedirect(reverse('account_login'))

        # if exists account with same email, redirect to login page with message
        user_email = self.sociallogin.user.email
        try:
            user = User.objects.get(email=user_email)
            messages.error(request, _('<strong>Login with e-mail and password</strong>\n'
                                      'You already create your account using the email and password. Please log in this way. '
                                      'After you log in, you will be able to use and login using Facebook.'), extra_tags='safe')
            return HttpResponseRedirect(reverse('account_login'))
        except User.DoesNotExist:
            return super(SignupView, self).dispatch(request, *args, **kwargs)
```

```python
# If user login via email/password, check if he attempt to connect via social network and automatically connect to his social network account.
@receiver(user_logged_in, dispatch_uid="allauth.account.signals.user_logged_in")
def auto_connect_social_account(request, user, **kwargs):
    """
    If user sucessfully login via social network, but he already has account (based on email),
    he is provoke to login via email. After logged in, this signal create connection between social network and user account.
    Next time user can use social network or email to login.
    """

    sociallogin = None
    data = request.session.get('socialaccount_sociallogin', None)
    if data:
        sociallogin = SocialLogin.deserialize(data)

    if not sociallogin:
        return

    if user.email != sociallogin.user.email:
        return

    _add_social_account(request, sociallogin)

    del request.session['socialaccount_sociallogin']
```

Better way should be directly improve django-allauth code. Do you think is it good idea?

**Comment by pennersr** [comment] 2015-10-16 20:40
Duplicate of #215

**Closed by pennersr** 2015-10-16 20:40 UTC

**Comment by pennersr** [comment] 2026-06-10 19:46
https://codeberg.org/allauth/django-allauth/issues/1149
