### ISSUE TITLE
TemplateSyntaxError at /accounts/login/

### ISSUE THREAD

**Issue by junior-r** [pennersr/django-allauth#3492] opened 2023-10-22 03:37 UTC
Hello, I´m using Django=4.2.6 and django-allauth=0.57.0, here is the error

'allauth' is not a registered tag library. Must be one of:
account
admin_list
admin_modify
admin_urls
cache
django_browser_reload
i18n
l10n
log
socialaccount
static
tailwind_tags
tz

_"GET /accounts/login/ HTTP/1.1" 500_

**Comment by pennersr** [comment] 2023-10-22 11:26
Dupe of #3472

**Closed** 2023-10-22 11:26 UTC

**Comment by pennersr** [comment] 2026-06-12 10:23
https://codeberg.org/allauth/django-allauth/issues/3492
