### ISSUE TITLE
Slack SocialAccount Error bad_redirect_uri

### ISSUE THREAD

**Issue by ManuelBuri** [pennersr/django-allauth#2878] opened 2021-06-01 17:42 UTC
Hi I am getting the following response as a callback from my call to the slack API:

`Code: unknown, Error: Error retrieving access token: b'{"ok":false,"error":"bad_redirect_uri"}'`

I have specified the redirect_uri in my call and it matches the entry in the slack app settings.

Any idea on how to solve/debug this?

**Comment by pennersr** [comment] 2021-12-10 14:24
Dupe of #2879

**Closed by pennersr** 2021-12-10 14:24 UTC

**Comment by pennersr** [comment] 2026-06-11 17:08
https://codeberg.org/allauth/django-allauth/issues/2878
