### ISSUE TITLE
Multiple Client IDs for one provider (Google) for different platforms (Web, iOS, Android)

### ISSUE THREAD

**Issue by Terspychore** [pennersr/django-allauth#3248] opened 2023-02-01 22:05 UTC
First of all, thank you for this amazing library,

Is there a way to manage multiple clients IDs for one provider (web, ios, android) ?

I have successfully done it with Apple using `client_id = '<app_id>, <service_id>'`, but when using this syntax for Google it does not work. (`The OAuth client was not found.`).

Moreover, only using one client_id does not work even if all of my IDs are in the same Google project. (getting the following error : `unauthorized_client`).

**Comment by oscarleonardoricci** [comment] 2023-12-12 15:04
From the source code it seems that most of the functions are built in a way that supports multiple social apps and client_ids for the same provider but with the standard adapters this doesn't seem to work out of the box.

**Comment by pennersr** [comment] 2023-12-12 16:41
Duplicate of https://github.com/pennersr/django-allauth/issues/1002

**Closed by pennersr** 2023-12-12 16:41 UTC

**Comment by pennersr** [comment] 2026-06-11 17:18
https://codeberg.org/allauth/django-allauth/issues/3248
