### ISSUE TITLE
Resend verification link of already confirmed email address

### ISSUE THREAD

**Issue by cyberjoac** [pennersr/django-allauth#806] opened 2015-01-10 16:46 UTC
Hi,

I noticed that you still have the option to resend confirmation email even if the mail is already confirmed.
Does that make sense?

Thanks a lot.

**Comment by pennersr** [comment] 2015-01-15 22:04
Duplicate of #754

**Closed by pennersr** 2015-01-15 22:04 UTC

**Comment by pennersr** [comment] 2026-06-10 17:29
https://codeberg.org/allauth/django-allauth/issues/806
