### ISSUE TITLE
Integrate allauth headless api docs with drf spectacular

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [pennersr/django-allauth#3813] opened 2024-05-14 17:58 UTC
Hi @pennersr ,
In my DRF application I use docs generated by [drf-spectacular](https://github.com/tfranzel/drf-spectacular).
Is there any workaround to integrate allauth headless docs into the same page. I don't want the front-end guys to go back and forth between two docs. Also is there any way to include swagger docs in this ?

I think the workaround here should be somehow serve the docs in my server itself, like if the drf-spectacular serves docs are at ```/docs/api/redoc/``` then the allauth should be hosted in ```/docs/api/redoc/allauth/```. But I'm not sure how to do it

**Comment by ashwanthbalakrishnan5** [comment] 2024-05-18 18:12
@pennersr Any updates on this ?

**Comment by pennersr** [comment] 2024-05-19 14:35
Duplicate of #3830

**Closed by pennersr** 2024-05-19 14:35 UTC

**Comment by pennersr** [comment] 2026-06-12 10:30
https://codeberg.org/allauth/django-allauth/issues/3813
