### ISSUE TITLE
IntegrityError for users_user_username_key at /accounts/signup/

### ISSUE THREAD

**Issue by berkerpeksag** [pennersr/django-allauth#1500] opened 2016-09-26 17:24 UTC
I sometimes get the following exception on www.python.org:

```py
IntegrityError: duplicate key value violates unique constraint "users_user_username_key"
DETAIL:  Key (username)=(XXXXX) already exists.

  File "django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "allauth/account/views.py", line 173, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "allauth/account/views.py", line 68, in dispatch
    **kwargs)
  File "allauth/account/views.py", line 151, in dispatch
    **kwargs)
  File "django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "allauth/account/views.py", line 84, in post
    response = self.form_valid(form)
  File "allauth/account/views.py", line 186, in form_valid
    user = form.save(self.request)
  File "allauth/account/forms.py", line 307, in save
    adapter.save_user(request, user, self)
  File "allauth/account/adapter.py", line 206, in save_user
    user.save()
  File "django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
```

Previously, we were getting a similar error because we were using a SignupForm subclass (which was wrong), but we don't use any custom forms anymore. And I cannot reproduce the problem on production.

Here is some information:

* allauth version: 0.22.0
* Django version: 1.7.11
* `AUTH_USER_MODEL` is `'users.User'` and it's a subclass of `AbstractUser`: https://github.com/python/pythondotorg/blob/master/users/models.py
* We are using the default signup view and form. The only place `allauth` is imported to test this behavior (duplicate username) in `users/tests/test_forms.py`: https://github.com/python/pythondotorg/blob/master/users/tests/test_forms.py
* allauth settings:

  ```py
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

LOGIN_REDIRECT_URL = 'home'
ACCOUNT_LOGOUT_REDIRECT_URL = 'home'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = True
SOCIALACCOUNT_QUERY_EMAIL = True
  ```

**Comment by pennersr** [comment] 2016-09-26 17:48
If you are receiving a sporadic IntegrityError it may be the case that the same request is being fired twice, for example due to the user accidentally double clicking the signup button. You may want to try disabling the submit button using a bit of JS...   could you try that and let me know if that addresses the issue?

**Comment by berkerpeksag** [comment] 2016-09-26 18:02
Thanks for the quick response. I haven't thought about that possibility. I just tried to reproduce it by clicking twice on the signup button, but it worked as expected.

**Comment by pennersr** [comment] 2016-09-26 18:04
If it is the issue I am referring to, then trying to reproduce it is quite difficult... as you basically need to recreate a race condition where at the right moment two requests are being interleaved.

**Comment by berkerpeksag** [comment] 2016-09-26 18:38
Good point, I've just implemented a solution in https://github.com/python/pythondotorg/commit/3b3a6e002bd0feceeacee5234c14fe218e792b67. I will deploy it today.

**Comment by vamsi** [comment] 2016-10-15 20:47
@berkerpeksag Thanks a lot, Helped me in production 🍰 .

**Comment by pennersr** [comment] 2016-10-17 11:07
Good to see confirmed that it is in fact the duplicate request issue. I am closing this, there is not much allauth can do to avoid it...

**Closed by pennersr** 2016-10-17 11:07 UTC
Labels: Unconfirmed

**Comment by pennersr** [comment] 2026-06-10 19:56
https://codeberg.org/allauth/django-allauth/issues/1500
