### ISSUE TITLE
[Bug] bound_field attributes such as Tabindex, autocomplete are not available in fields.html

### ISSUE THREAD

**Issue by akhileshThapliyal** [pennersr/django-allauth#4038] opened 2024-08-16 05:59 UTC
Hi Team,

I am trying to leverage on the base template for Bootstrap, I am facing the below errors. This is raised while accessing "allauth.account.views.LoginView". I have also observed that the some of bootstrap base templates in elements are a bit outdated. What should be my ideal approach in this case. Please let me know, thank you.

**Template Referred**: https://github.com/pennersr/django-allauth/blob/d6e07b22de047dfe3963e9385867be08be4f4501/examples/regular-django/example/templates/allauth/elements/fields.html

<img width="811" alt="image" src="https://github.com/user-attachments/assets/71e5fe81-d861-4d8e-8b44-68ae42b80ffa">

<img width="761" alt="image" src="https://github.com/user-attachments/assets/6d758c23-ba1a-47c8-a8b4-4e7b71d3ac21">

<img width="798" alt="image" src="https://github.com/user-attachments/assets/5d8b6fae-f179-43cf-b7e3-398cf4452b8f">

<img width="744" alt="image" src="https://github.com/user-attachments/assets/bc3bd26a-99fb-4894-9cdb-a330501610ab">

<img width="821" alt="image" src="https://github.com/user-attachments/assets/bd9df812-282c-4dae-ada7-2be4dd7c1b2e">

**Comment by pennersr** [comment] 2024-08-16 07:48
How does one reproduce this?

**Comment by akhileshThapliyal** [comment] 2024-08-16 08:25
> How does one reproduce this?

You add allauth to your new Django Project, copy the templates from the bootstrap example project and try to sign in. That's it.

I am also facing a similar issue with logout as well :(

<img width="817" alt="image" src="https://github.com/user-attachments/assets/9ec833c1-4b4c-4419-b2cf-3f51424c2fc5">

**Comment by pennersr** [comment] 2024-08-16 08:29
But the issue does not reproduce with a plain Django project. So I suspect that there are additional packages installed. Especially, the FastDevVariableDoesNotExist points to that. Are you using django-fastdev?

https://github.com/boxed/django-fastdev?tab=readme-ov-file#error-on-non-existent-template-variables

That may be the cause.

**Comment by akhileshThapliyal** [comment] 2024-08-16 08:38
> FastDevVariableDoesNotExist

yes, so I had to add conditional checks like below to get past the error. FastDev will not create issues, it is a debugging tool.

```py
{% if attrs.form %}
        {% for err in attrs.form.non_field_errors %}<div class="alert alert-danger">{{ err }}</div>{% endfor %}
{% endif %}
```

**Comment by akhileshThapliyal** [comment] 2024-08-16 08:39
> > FastDevVariableDoesNotExist
> 
> yes, so I had to add conditional checks like below to get past the error. FastDev will not create issues, it is a debugging tool.
> 
> ```python
> {% if attrs.form %}
>         {% for err in attrs.form.non_field_errors %}<div class="alert alert-danger">{{ err }}</div>{% endfor %}
> {% endif %}
> ```

My question is why are these attributes missing in some form and in some form they are present?

**Comment by pennersr** [comment] 2024-08-16 08:42
Closing for reasons mentioned here: #1427

> My question is why are these attributes missing

That part of the template is just forwarding any possible attribute that might exist to the element template.

**Closed by pennersr** 2024-08-16 08:42 UTC

**Comment by akhileshThapliyal** [comment] 2024-08-16 08:48
> Closing for reasons mentioned here: #1427
> 
> > My question is why are these attributes missing
> 
> That part of the template is just forwarding any possible attribute that might exist to the element template.

As per Django, it is not recommended to use the string_if_invalid settings in production. What I will do it add a check for each attribute, as I don't want to take shortcuts. Thank you :)

https://docs.djangoproject.com/en/4.2/ref/templates/api/#invalid-template-variables

<img width="863" alt="image" src="https://github.com/user-attachments/assets/1ecbb8cf-15d0-4a16-b4fb-e2aea5bcbef2">

**Comment by pennersr** [comment] 2026-06-12 10:35
https://codeberg.org/allauth/django-allauth/issues/4038
