### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by ghost** [pennersr/django-allauth#2549] opened 2020-05-23 02:15 UTC
How do you setup allauth with a custom OIDC client? Essentially my company provisions its own OpenID Connect credentials which includes .well-known/openid-configuration as per the OIDC standard, which defines a bunch of things include authentication/token endpoints as well as JOSE encryption. Once the code is exchanged for a token, that token can be decoded to reveal anything desired by the scope specified like profile for example, or any other claims.

How would I set this up in Django alongside React? Basically I want this external client to "sync" with the Django database such that an authenticated SSO user corresponds to a Django user as defined by that id token so that I can use permissions from Django.

**Comment by dbnicholson** [comment] 2020-06-04 04:23
This is a duplicate of #676. I don't think it would be that hard for someone to build on the OAuth2 provider and use a "brand" setup like the OpenID provider, but someone needs to write the code.

You could try django-oidc-rp or social-auth-app-django. They both can act as OIDC relying parties, but neither of them have all the forms and views that allauth has.

**Comment by phpfs** [comment] 2020-11-17 20:33
Hi there - any news to this? 👍

**Comment by debdolph** [comment] 2021-03-05 19:54
Any news?

**Comment by em-** [comment] 2023-01-16 14:25
I guess https://github.com/pennersr/django-allauth/pull/3165 solves this issue, part of the [0.52.0](https://github.com/pennersr/django-allauth/releases/tag/0.52.0) release.

**Closed** 2023-01-16 19:10 UTC

**Comment by pennersr** [comment] 2026-06-10 21:02
https://codeberg.org/allauth/django-allauth/issues/2549
