### ISSUE TITLE
SocialAccount Model crashes django migrations

### ISSUE THREAD

**Issue by pykler** [pennersr/django-allauth#811] opened 2015-01-18 07:28 UTC
Since choices list is dynamic, django (1.7) complains that the SocialAccount model is different from the database if not all of the providers are enabled. It forces the run of "manage.py makemigrations" which changes the choices on the `provider` field to whatever is enabled.

This perhaps is a bug with django itself, since choices on a charfield should not require a migration.

Thoughts?

**Comment by pykler** [comment] 2015-01-18 08:01
seems like something they don't want to change http://stackoverflow.com/a/26186194/742390

**Comment by pennersr** [comment] 2015-01-18 09:06
Dupe of #749

**Closed by pennersr** 2015-01-18 09:06 UTC

**Comment by pennersr** [comment] 2026-06-10 17:29
https://codeberg.org/allauth/django-allauth/issues/811
